package com.liketry.interaction.benison.model;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_admin.admin_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_admin.admin_code
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String adminCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_admin.login_name
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_admin.login_pwd
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String loginPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_admin.admin_name
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String adminName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_admin.admin_status
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String adminStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_admin.admin_mail
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String adminMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_admin.admin_phone
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String adminPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_admin.admin_id
     *
     * @return the value of bsc_admin.admin_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_admin.admin_id
     *
     * @param adminId the value for bsc_admin.admin_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setAdminId(String adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_admin.admin_code
     *
     * @return the value of bsc_admin.admin_code
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getAdminCode() {
        return adminCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_admin.admin_code
     *
     * @param adminCode the value for bsc_admin.admin_code
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setAdminCode(String adminCode) {
        this.adminCode = adminCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_admin.login_name
     *
     * @return the value of bsc_admin.login_name
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_admin.login_name
     *
     * @param loginName the value for bsc_admin.login_name
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_admin.login_pwd
     *
     * @return the value of bsc_admin.login_pwd
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getLoginPwd() {
        return loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_admin.login_pwd
     *
     * @param loginPwd the value for bsc_admin.login_pwd
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_admin.admin_name
     *
     * @return the value of bsc_admin.admin_name
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_admin.admin_name
     *
     * @param adminName the value for bsc_admin.admin_name
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_admin.admin_status
     *
     * @return the value of bsc_admin.admin_status
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getAdminStatus() {
        return adminStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_admin.admin_status
     *
     * @param adminStatus the value for bsc_admin.admin_status
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setAdminStatus(String adminStatus) {
        this.adminStatus = adminStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_admin.admin_mail
     *
     * @return the value of bsc_admin.admin_mail
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getAdminMail() {
        return adminMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_admin.admin_mail
     *
     * @param adminMail the value for bsc_admin.admin_mail
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setAdminMail(String adminMail) {
        this.adminMail = adminMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_admin.admin_phone
     *
     * @return the value of bsc_admin.admin_phone
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getAdminPhone() {
        return adminPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_admin.admin_phone
     *
     * @param adminPhone the value for bsc_admin.admin_phone
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setAdminPhone(String adminPhone) {
        this.adminPhone = adminPhone;
    }
}