package com.liketry.interaction.benison.model;

public class Benison {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison.benison_id
	 * @mbggenerated  Thu Aug 17 11:46:58 CST 2017
	 */
	private String benisonId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison.type_id
	 * @mbggenerated  Thu Aug 17 11:46:58 CST 2017
	 */
	private String typeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison.benison_code
	 * @mbggenerated  Thu Aug 17 11:46:58 CST 2017
	 */
	private String benisonCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison.benison_content
	 * @mbggenerated  Thu Aug 17 11:46:58 CST 2017
	 */
	private String benisonContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison.rule_content
	 * @mbggenerated  Thu Aug 17 11:46:58 CST 2017
	 */
	private String ruleContent;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison.benison_id
	 * @return  the value of bu_benison.benison_id
	 * @mbggenerated  Thu Aug 17 11:46:58 CST 2017
	 */
	public String getBenisonId() {
		return benisonId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison.benison_id
	 * @param benisonId  the value for bu_benison.benison_id
	 * @mbggenerated  Thu Aug 17 11:46:58 CST 2017
	 */
	public void setBenisonId(String benisonId) {
		this.benisonId = benisonId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison.type_id
	 * @return  the value of bu_benison.type_id
	 * @mbggenerated  Thu Aug 17 11:46:58 CST 2017
	 */
	public String getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison.type_id
	 * @param typeId  the value for bu_benison.type_id
	 * @mbggenerated  Thu Aug 17 11:46:58 CST 2017
	 */
	public void setTypeId(String typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison.benison_code
	 * @return  the value of bu_benison.benison_code
	 * @mbggenerated  Thu Aug 17 11:46:58 CST 2017
	 */
	public String getBenisonCode() {
		return benisonCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison.benison_code
	 * @param benisonCode  the value for bu_benison.benison_code
	 * @mbggenerated  Thu Aug 17 11:46:58 CST 2017
	 */
	public void setBenisonCode(String benisonCode) {
		this.benisonCode = benisonCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison.benison_content
	 * @return  the value of bu_benison.benison_content
	 * @mbggenerated  Thu Aug 17 11:46:58 CST 2017
	 */
	public String getBenisonContent() {
		return benisonContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison.benison_content
	 * @param benisonContent  the value for bu_benison.benison_content
	 * @mbggenerated  Thu Aug 17 11:46:58 CST 2017
	 */
	public void setBenisonContent(String benisonContent) {
		this.benisonContent = benisonContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison.rule_content
	 * @return  the value of bu_benison.rule_content
	 * @mbggenerated  Thu Aug 17 11:46:58 CST 2017
	 */
	public String getRuleContent() {
		return ruleContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison.rule_content
	 * @param ruleContent  the value for bu_benison.rule_content
	 * @mbggenerated  Thu Aug 17 11:46:58 CST 2017
	 */
	public void setRuleContent(String ruleContent) {
		this.ruleContent = ruleContent;
	}
}