package com.liketry.interaction.benison.model;

public class BenisonImg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_benison_img.img_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String imgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_benison_img.img_code
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String imgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_benison_img.img_name
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String imgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_benison_img.img_type
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String imgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_benison_img.img_url
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String imgUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_benison_img.img_id
     *
     * @return the value of bu_benison_img.img_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_benison_img.img_id
     *
     * @param imgId the value for bu_benison_img.img_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setImgId(String imgId) {
        this.imgId = imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_benison_img.img_code
     *
     * @return the value of bu_benison_img.img_code
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getImgCode() {
        return imgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_benison_img.img_code
     *
     * @param imgCode the value for bu_benison_img.img_code
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setImgCode(String imgCode) {
        this.imgCode = imgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_benison_img.img_name
     *
     * @return the value of bu_benison_img.img_name
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getImgName() {
        return imgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_benison_img.img_name
     *
     * @param imgName the value for bu_benison_img.img_name
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setImgName(String imgName) {
        this.imgName = imgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_benison_img.img_type
     *
     * @return the value of bu_benison_img.img_type
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getImgType() {
        return imgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_benison_img.img_type
     *
     * @param imgType the value for bu_benison_img.img_type
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setImgType(String imgType) {
        this.imgType = imgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_benison_img.img_url
     *
     * @return the value of bu_benison_img.img_url
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_benison_img.img_url
     *
     * @param imgUrl the value for bu_benison_img.img_url
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }
}