package com.liketry.interaction.benison.model;

public class BenisonTemplate {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison_template.template_id
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	private String templateId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison_template.template_code
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	private String templateCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison_template.template_name
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	private String templateName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison_template.screen_id
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	private String screenId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison_template.type_id
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	private String typeId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison_template.benison_id
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	private String benisonId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison_template.bg_img_id
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	private String bgImgId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison_template.sm_img_id
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	private String smImgId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison_template.title_x
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	private String titleX;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison_template.title_y
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	private String titleY;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison_template.title_colour
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	private String titleColour;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison_template.title_size
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	private String titleSize;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison_template.title_type
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	private String titleType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison_template.body_x
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	private String bodyX;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison_template.body_y
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	private String bodyY;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison_template.body_colour
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	private String bodyColour;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison_template.body_size
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	private String bodySize;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison_template.body_type
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	private String bodyType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison_template.tail_x
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	private String tailX;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison_template.tail_y
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	private String tailY;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison_template.tail_colour
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	private String tailColour;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison_template.tail_size
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	private String tailSize;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison_template.tail_type
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	private String tailType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison_template.stroke_figure
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	private String strokeFigure;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison_template.stroke_X
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	private String strokeX;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison_template.stroke_Y
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	private String strokeY;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison_template.stroke_alpha
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	private Float strokeAlpha;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison_template.template_id
	 * @return  the value of bu_benison_template.template_id
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public String getTemplateId() {
		return templateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison_template.template_id
	 * @param templateId  the value for bu_benison_template.template_id
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public void setTemplateId(String templateId) {
		this.templateId = templateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison_template.template_code
	 * @return  the value of bu_benison_template.template_code
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public String getTemplateCode() {
		return templateCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison_template.template_code
	 * @param templateCode  the value for bu_benison_template.template_code
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public void setTemplateCode(String templateCode) {
		this.templateCode = templateCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison_template.template_name
	 * @return  the value of bu_benison_template.template_name
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public String getTemplateName() {
		return templateName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison_template.template_name
	 * @param templateName  the value for bu_benison_template.template_name
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public void setTemplateName(String templateName) {
		this.templateName = templateName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison_template.screen_id
	 * @return  the value of bu_benison_template.screen_id
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public String getScreenId() {
		return screenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison_template.screen_id
	 * @param screenId  the value for bu_benison_template.screen_id
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public void setScreenId(String screenId) {
		this.screenId = screenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison_template.type_id
	 * @return  the value of bu_benison_template.type_id
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public String getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison_template.type_id
	 * @param typeId  the value for bu_benison_template.type_id
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public void setTypeId(String typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison_template.benison_id
	 * @return  the value of bu_benison_template.benison_id
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public String getBenisonId() {
		return benisonId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison_template.benison_id
	 * @param benisonId  the value for bu_benison_template.benison_id
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public void setBenisonId(String benisonId) {
		this.benisonId = benisonId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison_template.bg_img_id
	 * @return  the value of bu_benison_template.bg_img_id
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public String getBgImgId() {
		return bgImgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison_template.bg_img_id
	 * @param bgImgId  the value for bu_benison_template.bg_img_id
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public void setBgImgId(String bgImgId) {
		this.bgImgId = bgImgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison_template.sm_img_id
	 * @return  the value of bu_benison_template.sm_img_id
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public String getSmImgId() {
		return smImgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison_template.sm_img_id
	 * @param smImgId  the value for bu_benison_template.sm_img_id
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public void setSmImgId(String smImgId) {
		this.smImgId = smImgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison_template.title_x
	 * @return  the value of bu_benison_template.title_x
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public String getTitleX() {
		return titleX;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison_template.title_x
	 * @param titleX  the value for bu_benison_template.title_x
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public void setTitleX(String titleX) {
		this.titleX = titleX;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison_template.title_y
	 * @return  the value of bu_benison_template.title_y
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public String getTitleY() {
		return titleY;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison_template.title_y
	 * @param titleY  the value for bu_benison_template.title_y
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public void setTitleY(String titleY) {
		this.titleY = titleY;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison_template.title_colour
	 * @return  the value of bu_benison_template.title_colour
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public String getTitleColour() {
		return titleColour;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison_template.title_colour
	 * @param titleColour  the value for bu_benison_template.title_colour
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public void setTitleColour(String titleColour) {
		this.titleColour = titleColour;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison_template.title_size
	 * @return  the value of bu_benison_template.title_size
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public String getTitleSize() {
		return titleSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison_template.title_size
	 * @param titleSize  the value for bu_benison_template.title_size
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public void setTitleSize(String titleSize) {
		this.titleSize = titleSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison_template.title_type
	 * @return  the value of bu_benison_template.title_type
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public String getTitleType() {
		return titleType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison_template.title_type
	 * @param titleType  the value for bu_benison_template.title_type
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public void setTitleType(String titleType) {
		this.titleType = titleType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison_template.body_x
	 * @return  the value of bu_benison_template.body_x
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public String getBodyX() {
		return bodyX;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison_template.body_x
	 * @param bodyX  the value for bu_benison_template.body_x
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public void setBodyX(String bodyX) {
		this.bodyX = bodyX;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison_template.body_y
	 * @return  the value of bu_benison_template.body_y
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public String getBodyY() {
		return bodyY;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison_template.body_y
	 * @param bodyY  the value for bu_benison_template.body_y
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public void setBodyY(String bodyY) {
		this.bodyY = bodyY;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison_template.body_colour
	 * @return  the value of bu_benison_template.body_colour
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public String getBodyColour() {
		return bodyColour;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison_template.body_colour
	 * @param bodyColour  the value for bu_benison_template.body_colour
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public void setBodyColour(String bodyColour) {
		this.bodyColour = bodyColour;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison_template.body_size
	 * @return  the value of bu_benison_template.body_size
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public String getBodySize() {
		return bodySize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison_template.body_size
	 * @param bodySize  the value for bu_benison_template.body_size
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public void setBodySize(String bodySize) {
		this.bodySize = bodySize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison_template.body_type
	 * @return  the value of bu_benison_template.body_type
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public String getBodyType() {
		return bodyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison_template.body_type
	 * @param bodyType  the value for bu_benison_template.body_type
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public void setBodyType(String bodyType) {
		this.bodyType = bodyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison_template.tail_x
	 * @return  the value of bu_benison_template.tail_x
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public String getTailX() {
		return tailX;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison_template.tail_x
	 * @param tailX  the value for bu_benison_template.tail_x
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public void setTailX(String tailX) {
		this.tailX = tailX;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison_template.tail_y
	 * @return  the value of bu_benison_template.tail_y
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public String getTailY() {
		return tailY;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison_template.tail_y
	 * @param tailY  the value for bu_benison_template.tail_y
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public void setTailY(String tailY) {
		this.tailY = tailY;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison_template.tail_colour
	 * @return  the value of bu_benison_template.tail_colour
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public String getTailColour() {
		return tailColour;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison_template.tail_colour
	 * @param tailColour  the value for bu_benison_template.tail_colour
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public void setTailColour(String tailColour) {
		this.tailColour = tailColour;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison_template.tail_size
	 * @return  the value of bu_benison_template.tail_size
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public String getTailSize() {
		return tailSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison_template.tail_size
	 * @param tailSize  the value for bu_benison_template.tail_size
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public void setTailSize(String tailSize) {
		this.tailSize = tailSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison_template.tail_type
	 * @return  the value of bu_benison_template.tail_type
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public String getTailType() {
		return tailType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison_template.tail_type
	 * @param tailType  the value for bu_benison_template.tail_type
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public void setTailType(String tailType) {
		this.tailType = tailType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison_template.stroke_figure
	 * @return  the value of bu_benison_template.stroke_figure
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public String getStrokeFigure() {
		return strokeFigure;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison_template.stroke_figure
	 * @param strokeFigure  the value for bu_benison_template.stroke_figure
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public void setStrokeFigure(String strokeFigure) {
		this.strokeFigure = strokeFigure;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison_template.stroke_X
	 * @return  the value of bu_benison_template.stroke_X
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public String getStrokeX() {
		return strokeX;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison_template.stroke_X
	 * @param strokeX  the value for bu_benison_template.stroke_X
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public void setStrokeX(String strokeX) {
		this.strokeX = strokeX;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison_template.stroke_Y
	 * @return  the value of bu_benison_template.stroke_Y
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public String getStrokeY() {
		return strokeY;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison_template.stroke_Y
	 * @param strokeY  the value for bu_benison_template.stroke_Y
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public void setStrokeY(String strokeY) {
		this.strokeY = strokeY;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison_template.stroke_alpha
	 * @return  the value of bu_benison_template.stroke_alpha
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public Float getStrokeAlpha() {
		return strokeAlpha;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison_template.stroke_alpha
	 * @param strokeAlpha  the value for bu_benison_template.stroke_alpha
	 * @mbggenerated  Wed Oct 18 16:23:02 CST 2017
	 */
	public void setStrokeAlpha(Float strokeAlpha) {
		this.strokeAlpha = strokeAlpha;
	}

	private String ruleContent;
    
    private String imgUrl;

	public String getRuleContent() {
		return ruleContent;
	}

	public void setRuleContent(String ruleContent) {
		this.ruleContent = ruleContent;
	}

	public String getImgUrl() {
		return imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}
    
    
    
    
}