package com.liketry.interaction.benison.model;

public class BenisonType {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison_type.type_id
	 * @mbggenerated  Thu Sep 28 13:48:05 CST 2017
	 */
	private String typeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison_type.type_code
	 * @mbggenerated  Thu Sep 28 13:48:05 CST 2017
	 */
	private String typeCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison_type.type_name
	 * @mbggenerated  Thu Sep 28 13:48:05 CST 2017
	 */
	private String typeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison_type.effect_flag
	 * @mbggenerated  Thu Sep 28 13:48:05 CST 2017
	 */
	private String effectFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_benison_type.sort_num
	 * @mbggenerated  Thu Sep 28 13:48:05 CST 2017
	 */
	private Integer sortNum;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison_type.type_id
	 * @return  the value of bu_benison_type.type_id
	 * @mbggenerated  Thu Sep 28 13:48:05 CST 2017
	 */
	public String getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison_type.type_id
	 * @param typeId  the value for bu_benison_type.type_id
	 * @mbggenerated  Thu Sep 28 13:48:05 CST 2017
	 */
	public void setTypeId(String typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison_type.type_code
	 * @return  the value of bu_benison_type.type_code
	 * @mbggenerated  Thu Sep 28 13:48:05 CST 2017
	 */
	public String getTypeCode() {
		return typeCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison_type.type_code
	 * @param typeCode  the value for bu_benison_type.type_code
	 * @mbggenerated  Thu Sep 28 13:48:05 CST 2017
	 */
	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison_type.type_name
	 * @return  the value of bu_benison_type.type_name
	 * @mbggenerated  Thu Sep 28 13:48:05 CST 2017
	 */
	public String getTypeName() {
		return typeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison_type.type_name
	 * @param typeName  the value for bu_benison_type.type_name
	 * @mbggenerated  Thu Sep 28 13:48:05 CST 2017
	 */
	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison_type.effect_flag
	 * @return  the value of bu_benison_type.effect_flag
	 * @mbggenerated  Thu Sep 28 13:48:05 CST 2017
	 */
	public String getEffectFlag() {
		return effectFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison_type.effect_flag
	 * @param effectFlag  the value for bu_benison_type.effect_flag
	 * @mbggenerated  Thu Sep 28 13:48:05 CST 2017
	 */
	public void setEffectFlag(String effectFlag) {
		this.effectFlag = effectFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_benison_type.sort_num
	 * @return  the value of bu_benison_type.sort_num
	 * @mbggenerated  Thu Sep 28 13:48:05 CST 2017
	 */
	public Integer getSortNum() {
		return sortNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_benison_type.sort_num
	 * @param sortNum  the value for bu_benison_type.sort_num
	 * @mbggenerated  Thu Sep 28 13:48:05 CST 2017
	 */
	public void setSortNum(Integer sortNum) {
		this.sortNum = sortNum;
	}
}