package com.liketry.interaction.benison.model;

public class BizSeqno {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bsc_biz_seqno_t.Seq_Type
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	private String seqType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bsc_biz_seqno_t.seq_prefix
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	private String seqPrefix;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bsc_biz_seqno_t.seq_suffix
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	private String seqSuffix;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bsc_biz_seqno_t.place_holder
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	private String placeHolder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bsc_biz_seqno_t.align_type
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	private String alignType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bsc_biz_seqno_t.curr_value
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	private Integer currValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bsc_biz_seqno_t.t_increment
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	private Integer tIncrement;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bsc_biz_seqno_t.init_value
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	private Integer initValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bsc_biz_seqno_t.max_value
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	private Integer maxValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bsc_biz_seqno_t.max_length
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	private Integer maxLength;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bsc_biz_seqno_t.cache_num
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	private Integer cacheNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bsc_biz_seqno_t.t_explain
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	private String tExplain;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bsc_biz_seqno_t.Seq_Type
	 * @return  the value of bsc_biz_seqno_t.Seq_Type
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	public String getSeqType() {
		return seqType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bsc_biz_seqno_t.Seq_Type
	 * @param seqType  the value for bsc_biz_seqno_t.Seq_Type
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	public void setSeqType(String seqType) {
		this.seqType = seqType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bsc_biz_seqno_t.seq_prefix
	 * @return  the value of bsc_biz_seqno_t.seq_prefix
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	public String getSeqPrefix() {
		return seqPrefix;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bsc_biz_seqno_t.seq_prefix
	 * @param seqPrefix  the value for bsc_biz_seqno_t.seq_prefix
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	public void setSeqPrefix(String seqPrefix) {
		this.seqPrefix = seqPrefix;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bsc_biz_seqno_t.seq_suffix
	 * @return  the value of bsc_biz_seqno_t.seq_suffix
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	public String getSeqSuffix() {
		return seqSuffix;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bsc_biz_seqno_t.seq_suffix
	 * @param seqSuffix  the value for bsc_biz_seqno_t.seq_suffix
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	public void setSeqSuffix(String seqSuffix) {
		this.seqSuffix = seqSuffix;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bsc_biz_seqno_t.place_holder
	 * @return  the value of bsc_biz_seqno_t.place_holder
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	public String getPlaceHolder() {
		return placeHolder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bsc_biz_seqno_t.place_holder
	 * @param placeHolder  the value for bsc_biz_seqno_t.place_holder
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	public void setPlaceHolder(String placeHolder) {
		this.placeHolder = placeHolder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bsc_biz_seqno_t.align_type
	 * @return  the value of bsc_biz_seqno_t.align_type
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	public String getAlignType() {
		return alignType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bsc_biz_seqno_t.align_type
	 * @param alignType  the value for bsc_biz_seqno_t.align_type
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	public void setAlignType(String alignType) {
		this.alignType = alignType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bsc_biz_seqno_t.curr_value
	 * @return  the value of bsc_biz_seqno_t.curr_value
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	public Integer getCurrValue() {
		return currValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bsc_biz_seqno_t.curr_value
	 * @param currValue  the value for bsc_biz_seqno_t.curr_value
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	public void setCurrValue(Integer currValue) {
		this.currValue = currValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bsc_biz_seqno_t.t_increment
	 * @return  the value of bsc_biz_seqno_t.t_increment
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	public Integer gettIncrement() {
		return tIncrement;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bsc_biz_seqno_t.t_increment
	 * @param tIncrement  the value for bsc_biz_seqno_t.t_increment
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	public void settIncrement(Integer tIncrement) {
		this.tIncrement = tIncrement;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bsc_biz_seqno_t.init_value
	 * @return  the value of bsc_biz_seqno_t.init_value
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	public Integer getInitValue() {
		return initValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bsc_biz_seqno_t.init_value
	 * @param initValue  the value for bsc_biz_seqno_t.init_value
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	public void setInitValue(Integer initValue) {
		this.initValue = initValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bsc_biz_seqno_t.max_value
	 * @return  the value of bsc_biz_seqno_t.max_value
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	public Integer getMaxValue() {
		return maxValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bsc_biz_seqno_t.max_value
	 * @param maxValue  the value for bsc_biz_seqno_t.max_value
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	public void setMaxValue(Integer maxValue) {
		this.maxValue = maxValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bsc_biz_seqno_t.max_length
	 * @return  the value of bsc_biz_seqno_t.max_length
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	public Integer getMaxLength() {
		return maxLength;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bsc_biz_seqno_t.max_length
	 * @param maxLength  the value for bsc_biz_seqno_t.max_length
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	public void setMaxLength(Integer maxLength) {
		this.maxLength = maxLength;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bsc_biz_seqno_t.cache_num
	 * @return  the value of bsc_biz_seqno_t.cache_num
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	public Integer getCacheNum() {
		return cacheNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bsc_biz_seqno_t.cache_num
	 * @param cacheNum  the value for bsc_biz_seqno_t.cache_num
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	public void setCacheNum(Integer cacheNum) {
		this.cacheNum = cacheNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bsc_biz_seqno_t.t_explain
	 * @return  the value of bsc_biz_seqno_t.t_explain
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	public String gettExplain() {
		return tExplain;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bsc_biz_seqno_t.t_explain
	 * @param tExplain  the value for bsc_biz_seqno_t.t_explain
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	public void settExplain(String tExplain) {
		this.tExplain = tExplain;
	}
}