package com.liketry.interaction.benison.model;

import java.math.BigDecimal;
import java.util.Date;

public class CommoditySku {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity_sku.sku_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String skuId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity_sku.commodity_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String commodityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity_sku.sku_code
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String skuCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity_sku.sku_name
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String skuName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity_sku.sku_description
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String skuDescription;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity_sku.sku_status
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String skuStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity_sku.sku_price
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private BigDecimal skuPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity_sku.template_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String templateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity_sku.type_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String typeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity_sku.benison_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String benisonId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity_sku.created_time
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private Date createdTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity_sku.created_by
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String createdBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity_sku.modified_time
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private Date modifiedTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity_sku.modified_by
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String modifiedBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity_sku.version
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity_sku.delflag
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String delflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity_sku.sku_id
	 * @return  the value of bu_commodity_sku.sku_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getSkuId() {
		return skuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity_sku.sku_id
	 * @param skuId  the value for bu_commodity_sku.sku_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setSkuId(String skuId) {
		this.skuId = skuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity_sku.commodity_id
	 * @return  the value of bu_commodity_sku.commodity_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getCommodityId() {
		return commodityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity_sku.commodity_id
	 * @param commodityId  the value for bu_commodity_sku.commodity_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setCommodityId(String commodityId) {
		this.commodityId = commodityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity_sku.sku_code
	 * @return  the value of bu_commodity_sku.sku_code
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getSkuCode() {
		return skuCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity_sku.sku_code
	 * @param skuCode  the value for bu_commodity_sku.sku_code
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setSkuCode(String skuCode) {
		this.skuCode = skuCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity_sku.sku_name
	 * @return  the value of bu_commodity_sku.sku_name
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getSkuName() {
		return skuName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity_sku.sku_name
	 * @param skuName  the value for bu_commodity_sku.sku_name
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setSkuName(String skuName) {
		this.skuName = skuName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity_sku.sku_description
	 * @return  the value of bu_commodity_sku.sku_description
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getSkuDescription() {
		return skuDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity_sku.sku_description
	 * @param skuDescription  the value for bu_commodity_sku.sku_description
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setSkuDescription(String skuDescription) {
		this.skuDescription = skuDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity_sku.sku_status
	 * @return  the value of bu_commodity_sku.sku_status
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getSkuStatus() {
		return skuStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity_sku.sku_status
	 * @param skuStatus  the value for bu_commodity_sku.sku_status
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setSkuStatus(String skuStatus) {
		this.skuStatus = skuStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity_sku.sku_price
	 * @return  the value of bu_commodity_sku.sku_price
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public BigDecimal getSkuPrice() {
		return skuPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity_sku.sku_price
	 * @param skuPrice  the value for bu_commodity_sku.sku_price
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setSkuPrice(BigDecimal skuPrice) {
		this.skuPrice = skuPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity_sku.template_id
	 * @return  the value of bu_commodity_sku.template_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getTemplateId() {
		return templateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity_sku.template_id
	 * @param templateId  the value for bu_commodity_sku.template_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setTemplateId(String templateId) {
		this.templateId = templateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity_sku.type_id
	 * @return  the value of bu_commodity_sku.type_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity_sku.type_id
	 * @param typeId  the value for bu_commodity_sku.type_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setTypeId(String typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity_sku.benison_id
	 * @return  the value of bu_commodity_sku.benison_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getBenisonId() {
		return benisonId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity_sku.benison_id
	 * @param benisonId  the value for bu_commodity_sku.benison_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setBenisonId(String benisonId) {
		this.benisonId = benisonId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity_sku.created_time
	 * @return  the value of bu_commodity_sku.created_time
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public Date getCreatedTime() {
		return createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity_sku.created_time
	 * @param createdTime  the value for bu_commodity_sku.created_time
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity_sku.created_by
	 * @return  the value of bu_commodity_sku.created_by
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity_sku.created_by
	 * @param createdBy  the value for bu_commodity_sku.created_by
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity_sku.modified_time
	 * @return  the value of bu_commodity_sku.modified_time
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public Date getModifiedTime() {
		return modifiedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity_sku.modified_time
	 * @param modifiedTime  the value for bu_commodity_sku.modified_time
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity_sku.modified_by
	 * @return  the value of bu_commodity_sku.modified_by
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getModifiedBy() {
		return modifiedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity_sku.modified_by
	 * @param modifiedBy  the value for bu_commodity_sku.modified_by
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity_sku.version
	 * @return  the value of bu_commodity_sku.version
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity_sku.version
	 * @param version  the value for bu_commodity_sku.version
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity_sku.delflag
	 * @return  the value of bu_commodity_sku.delflag
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getDelflag() {
		return delflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity_sku.delflag
	 * @param delflag  the value for bu_commodity_sku.delflag
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setDelflag(String delflag) {
		this.delflag = delflag;
	}
}