package com.liketry.interaction.benison.model;

import java.math.BigDecimal;

public class CommodityCost {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity_cost.cost_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String costId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity_cost.commodity_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String commodityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity_cost.sku_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String skuId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity_cost.cost_type
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String costType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity_cost.cost_name
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String costName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity_cost.cost_price
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private BigDecimal costPrice;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity_cost.cost_id
	 * @return  the value of bu_commodity_cost.cost_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getCostId() {
		return costId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity_cost.cost_id
	 * @param costId  the value for bu_commodity_cost.cost_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setCostId(String costId) {
		this.costId = costId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity_cost.commodity_id
	 * @return  the value of bu_commodity_cost.commodity_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getCommodityId() {
		return commodityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity_cost.commodity_id
	 * @param commodityId  the value for bu_commodity_cost.commodity_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setCommodityId(String commodityId) {
		this.commodityId = commodityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity_cost.sku_id
	 * @return  the value of bu_commodity_cost.sku_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getSkuId() {
		return skuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity_cost.sku_id
	 * @param skuId  the value for bu_commodity_cost.sku_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setSkuId(String skuId) {
		this.skuId = skuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity_cost.cost_type
	 * @return  the value of bu_commodity_cost.cost_type
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getCostType() {
		return costType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity_cost.cost_type
	 * @param costType  the value for bu_commodity_cost.cost_type
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setCostType(String costType) {
		this.costType = costType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity_cost.cost_name
	 * @return  the value of bu_commodity_cost.cost_name
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getCostName() {
		return costName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity_cost.cost_name
	 * @param costName  the value for bu_commodity_cost.cost_name
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setCostName(String costName) {
		this.costName = costName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity_cost.cost_price
	 * @return  the value of bu_commodity_cost.cost_price
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public BigDecimal getCostPrice() {
		return costPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity_cost.cost_price
	 * @param costPrice  the value for bu_commodity_cost.cost_price
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setCostPrice(BigDecimal costPrice) {
		this.costPrice = costPrice;
	}
}