package com.liketry.interaction.benison.model;

import java.math.BigDecimal;
import java.util.Date;

public class Commodity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity.commodity_id
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	private String commodityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity.commodity_code
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	private String commodityCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity.commodity_name
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	private String commodityName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity.commodity_description
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	private String commodityDescription;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity.commodity_type
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	private String commodityType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity.commodity_status
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	private String commodityStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity.commodity_price
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	private BigDecimal commodityPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity.commodity_img
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	private String commodityImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity.screen_id
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	private String screenId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity.start_date
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	private String startDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity.end_date
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	private String endDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity.time_frame
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	private String timeFrame;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity.start_time
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	private String startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity.end_time
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	private String endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity.shelf_time
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	private String shelfTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity.plan_number
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	private Integer planNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity.single_time
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	private Integer singleTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity.play_times
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	private Integer playTimes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity.created_time
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	private Date createdTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity.created_by
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	private String createdBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity.modified_time
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	private Date modifiedTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity.modified_by
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	private String modifiedBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity.version
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_commodity.delflag
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	private String delflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity.commodity_id
	 * @return  the value of bu_commodity.commodity_id
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public String getCommodityId() {
		return commodityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity.commodity_id
	 * @param commodityId  the value for bu_commodity.commodity_id
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public void setCommodityId(String commodityId) {
		this.commodityId = commodityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity.commodity_code
	 * @return  the value of bu_commodity.commodity_code
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public String getCommodityCode() {
		return commodityCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity.commodity_code
	 * @param commodityCode  the value for bu_commodity.commodity_code
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public void setCommodityCode(String commodityCode) {
		this.commodityCode = commodityCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity.commodity_name
	 * @return  the value of bu_commodity.commodity_name
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public String getCommodityName() {
		return commodityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity.commodity_name
	 * @param commodityName  the value for bu_commodity.commodity_name
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public void setCommodityName(String commodityName) {
		this.commodityName = commodityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity.commodity_description
	 * @return  the value of bu_commodity.commodity_description
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public String getCommodityDescription() {
		return commodityDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity.commodity_description
	 * @param commodityDescription  the value for bu_commodity.commodity_description
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public void setCommodityDescription(String commodityDescription) {
		this.commodityDescription = commodityDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity.commodity_type
	 * @return  the value of bu_commodity.commodity_type
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public String getCommodityType() {
		return commodityType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity.commodity_type
	 * @param commodityType  the value for bu_commodity.commodity_type
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public void setCommodityType(String commodityType) {
		this.commodityType = commodityType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity.commodity_status
	 * @return  the value of bu_commodity.commodity_status
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public String getCommodityStatus() {
		return commodityStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity.commodity_status
	 * @param commodityStatus  the value for bu_commodity.commodity_status
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public void setCommodityStatus(String commodityStatus) {
		this.commodityStatus = commodityStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity.commodity_price
	 * @return  the value of bu_commodity.commodity_price
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public BigDecimal getCommodityPrice() {
		return commodityPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity.commodity_price
	 * @param commodityPrice  the value for bu_commodity.commodity_price
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public void setCommodityPrice(BigDecimal commodityPrice) {
		this.commodityPrice = commodityPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity.commodity_img
	 * @return  the value of bu_commodity.commodity_img
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public String getCommodityImg() {
		return commodityImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity.commodity_img
	 * @param commodityImg  the value for bu_commodity.commodity_img
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public void setCommodityImg(String commodityImg) {
		this.commodityImg = commodityImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity.screen_id
	 * @return  the value of bu_commodity.screen_id
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public String getScreenId() {
		return screenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity.screen_id
	 * @param screenId  the value for bu_commodity.screen_id
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public void setScreenId(String screenId) {
		this.screenId = screenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity.start_date
	 * @return  the value of bu_commodity.start_date
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public String getStartDate() {
		return startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity.start_date
	 * @param startDate  the value for bu_commodity.start_date
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity.end_date
	 * @return  the value of bu_commodity.end_date
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public String getEndDate() {
		return endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity.end_date
	 * @param endDate  the value for bu_commodity.end_date
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity.time_frame
	 * @return  the value of bu_commodity.time_frame
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public String getTimeFrame() {
		return timeFrame;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity.time_frame
	 * @param timeFrame  the value for bu_commodity.time_frame
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public void setTimeFrame(String timeFrame) {
		this.timeFrame = timeFrame;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity.start_time
	 * @return  the value of bu_commodity.start_time
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public String getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity.start_time
	 * @param startTime  the value for bu_commodity.start_time
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity.end_time
	 * @return  the value of bu_commodity.end_time
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public String getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity.end_time
	 * @param endTime  the value for bu_commodity.end_time
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity.shelf_time
	 * @return  the value of bu_commodity.shelf_time
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public String getShelfTime() {
		return shelfTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity.shelf_time
	 * @param shelfTime  the value for bu_commodity.shelf_time
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public void setShelfTime(String shelfTime) {
		this.shelfTime = shelfTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity.plan_number
	 * @return  the value of bu_commodity.plan_number
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public Integer getPlanNumber() {
		return planNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity.plan_number
	 * @param planNumber  the value for bu_commodity.plan_number
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public void setPlanNumber(Integer planNumber) {
		this.planNumber = planNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity.single_time
	 * @return  the value of bu_commodity.single_time
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public Integer getSingleTime() {
		return singleTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity.single_time
	 * @param singleTime  the value for bu_commodity.single_time
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public void setSingleTime(Integer singleTime) {
		this.singleTime = singleTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity.play_times
	 * @return  the value of bu_commodity.play_times
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public Integer getPlayTimes() {
		return playTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity.play_times
	 * @param playTimes  the value for bu_commodity.play_times
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public void setPlayTimes(Integer playTimes) {
		this.playTimes = playTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity.created_time
	 * @return  the value of bu_commodity.created_time
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public Date getCreatedTime() {
		return createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity.created_time
	 * @param createdTime  the value for bu_commodity.created_time
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity.created_by
	 * @return  the value of bu_commodity.created_by
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public String getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity.created_by
	 * @param createdBy  the value for bu_commodity.created_by
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity.modified_time
	 * @return  the value of bu_commodity.modified_time
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public Date getModifiedTime() {
		return modifiedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity.modified_time
	 * @param modifiedTime  the value for bu_commodity.modified_time
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity.modified_by
	 * @return  the value of bu_commodity.modified_by
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public String getModifiedBy() {
		return modifiedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity.modified_by
	 * @param modifiedBy  the value for bu_commodity.modified_by
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity.version
	 * @return  the value of bu_commodity.version
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity.version
	 * @param version  the value for bu_commodity.version
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_commodity.delflag
	 * @return  the value of bu_commodity.delflag
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public String getDelflag() {
		return delflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_commodity.delflag
	 * @param delflag  the value for bu_commodity.delflag
	 * @mbggenerated  Tue Jul 04 10:30:30 CST 2017
	 */
	public void setDelflag(String delflag) {
		this.delflag = delflag;
	}
}