package com.liketry.interaction.benison.model;

import java.math.BigDecimal;
import java.util.Date;

public class ConfCustom {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_conf_custom.custom_id
	 * @mbggenerated  Mon Aug 14 10:04:37 CST 2017
	 */
	private String customId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_conf_custom.custom_type
	 * @mbggenerated  Mon Aug 14 10:04:37 CST 2017
	 */
	private String customType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_conf_custom.custom_price
	 * @mbggenerated  Mon Aug 14 10:04:37 CST 2017
	 */
	private BigDecimal customPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_conf_custom.created_time
	 * @mbggenerated  Mon Aug 14 10:04:37 CST 2017
	 */
	private Date createdTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_conf_custom.created_by
	 * @mbggenerated  Mon Aug 14 10:04:37 CST 2017
	 */
	private String createdBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_conf_custom.modified_time
	 * @mbggenerated  Mon Aug 14 10:04:37 CST 2017
	 */
	private Date modifiedTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_conf_custom.modified_by
	 * @mbggenerated  Mon Aug 14 10:04:37 CST 2017
	 */
	private String modifiedBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_conf_custom.version
	 * @mbggenerated  Mon Aug 14 10:04:37 CST 2017
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_conf_custom.delflag
	 * @mbggenerated  Mon Aug 14 10:04:37 CST 2017
	 */
	private String delflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_conf_custom.custom_id
	 * @return  the value of bu_conf_custom.custom_id
	 * @mbggenerated  Mon Aug 14 10:04:37 CST 2017
	 */
	public String getCustomId() {
		return customId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_conf_custom.custom_id
	 * @param customId  the value for bu_conf_custom.custom_id
	 * @mbggenerated  Mon Aug 14 10:04:37 CST 2017
	 */
	public void setCustomId(String customId) {
		this.customId = customId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_conf_custom.custom_type
	 * @return  the value of bu_conf_custom.custom_type
	 * @mbggenerated  Mon Aug 14 10:04:37 CST 2017
	 */
	public String getCustomType() {
		return customType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_conf_custom.custom_type
	 * @param customType  the value for bu_conf_custom.custom_type
	 * @mbggenerated  Mon Aug 14 10:04:37 CST 2017
	 */
	public void setCustomType(String customType) {
		this.customType = customType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_conf_custom.custom_price
	 * @return  the value of bu_conf_custom.custom_price
	 * @mbggenerated  Mon Aug 14 10:04:37 CST 2017
	 */
	public BigDecimal getCustomPrice() {
		return customPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_conf_custom.custom_price
	 * @param customPrice  the value for bu_conf_custom.custom_price
	 * @mbggenerated  Mon Aug 14 10:04:37 CST 2017
	 */
	public void setCustomPrice(BigDecimal customPrice) {
		this.customPrice = customPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_conf_custom.created_time
	 * @return  the value of bu_conf_custom.created_time
	 * @mbggenerated  Mon Aug 14 10:04:37 CST 2017
	 */
	public Date getCreatedTime() {
		return createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_conf_custom.created_time
	 * @param createdTime  the value for bu_conf_custom.created_time
	 * @mbggenerated  Mon Aug 14 10:04:37 CST 2017
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_conf_custom.created_by
	 * @return  the value of bu_conf_custom.created_by
	 * @mbggenerated  Mon Aug 14 10:04:37 CST 2017
	 */
	public String getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_conf_custom.created_by
	 * @param createdBy  the value for bu_conf_custom.created_by
	 * @mbggenerated  Mon Aug 14 10:04:37 CST 2017
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_conf_custom.modified_time
	 * @return  the value of bu_conf_custom.modified_time
	 * @mbggenerated  Mon Aug 14 10:04:37 CST 2017
	 */
	public Date getModifiedTime() {
		return modifiedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_conf_custom.modified_time
	 * @param modifiedTime  the value for bu_conf_custom.modified_time
	 * @mbggenerated  Mon Aug 14 10:04:37 CST 2017
	 */
	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_conf_custom.modified_by
	 * @return  the value of bu_conf_custom.modified_by
	 * @mbggenerated  Mon Aug 14 10:04:37 CST 2017
	 */
	public String getModifiedBy() {
		return modifiedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_conf_custom.modified_by
	 * @param modifiedBy  the value for bu_conf_custom.modified_by
	 * @mbggenerated  Mon Aug 14 10:04:37 CST 2017
	 */
	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_conf_custom.version
	 * @return  the value of bu_conf_custom.version
	 * @mbggenerated  Mon Aug 14 10:04:37 CST 2017
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_conf_custom.version
	 * @param version  the value for bu_conf_custom.version
	 * @mbggenerated  Mon Aug 14 10:04:37 CST 2017
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_conf_custom.delflag
	 * @return  the value of bu_conf_custom.delflag
	 * @mbggenerated  Mon Aug 14 10:04:37 CST 2017
	 */
	public String getDelflag() {
		return delflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_conf_custom.delflag
	 * @param delflag  the value for bu_conf_custom.delflag
	 * @mbggenerated  Mon Aug 14 10:04:37 CST 2017
	 */
	public void setDelflag(String delflag) {
		this.delflag = delflag;
	}
}