package com.liketry.interaction.benison.model;

import java.math.BigDecimal;
import java.util.Date;

public class CouponType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon_type.coupon_type_id
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private String couponTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon_type.coupon_type_code
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private String couponTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon_type.coupon_name
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private String couponName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon_type.coupon_type
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private String couponType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon_type.valid_type
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private String validType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon_type.publish_type
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private String publishType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon_type.special_offer
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private BigDecimal specialOffer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon_type.discount
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private BigDecimal discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon_type.deduction
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private BigDecimal deduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon_type.screen_ids
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private String screenIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon_type.commodity_ids
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private String commodityIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon_type.benison_type_ids
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private String benisonTypeIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon_type.created_time
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon_type.created_by
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon_type.modified_time
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon_type.modified_by
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private String modifiedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon_type.version
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon_type.delflag
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private String delflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon_type.coupon_type_id
     *
     * @return the value of bu_coupon_type.coupon_type_id
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public String getCouponTypeId() {
        return couponTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon_type.coupon_type_id
     *
     * @param couponTypeId the value for bu_coupon_type.coupon_type_id
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setCouponTypeId(String couponTypeId) {
        this.couponTypeId = couponTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon_type.coupon_type_code
     *
     * @return the value of bu_coupon_type.coupon_type_code
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public String getCouponTypeCode() {
        return couponTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon_type.coupon_type_code
     *
     * @param couponTypeCode the value for bu_coupon_type.coupon_type_code
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setCouponTypeCode(String couponTypeCode) {
        this.couponTypeCode = couponTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon_type.coupon_name
     *
     * @return the value of bu_coupon_type.coupon_name
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public String getCouponName() {
        return couponName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon_type.coupon_name
     *
     * @param couponName the value for bu_coupon_type.coupon_name
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setCouponName(String couponName) {
        this.couponName = couponName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon_type.coupon_type
     *
     * @return the value of bu_coupon_type.coupon_type
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public String getCouponType() {
        return couponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon_type.coupon_type
     *
     * @param couponType the value for bu_coupon_type.coupon_type
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setCouponType(String couponType) {
        this.couponType = couponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon_type.valid_type
     *
     * @return the value of bu_coupon_type.valid_type
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public String getValidType() {
        return validType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon_type.valid_type
     *
     * @param validType the value for bu_coupon_type.valid_type
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setValidType(String validType) {
        this.validType = validType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon_type.publish_type
     *
     * @return the value of bu_coupon_type.publish_type
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public String getPublishType() {
        return publishType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon_type.publish_type
     *
     * @param publishType the value for bu_coupon_type.publish_type
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setPublishType(String publishType) {
        this.publishType = publishType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon_type.special_offer
     *
     * @return the value of bu_coupon_type.special_offer
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public BigDecimal getSpecialOffer() {
        return specialOffer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon_type.special_offer
     *
     * @param specialOffer the value for bu_coupon_type.special_offer
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setSpecialOffer(BigDecimal specialOffer) {
        this.specialOffer = specialOffer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon_type.discount
     *
     * @return the value of bu_coupon_type.discount
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon_type.discount
     *
     * @param discount the value for bu_coupon_type.discount
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon_type.deduction
     *
     * @return the value of bu_coupon_type.deduction
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public BigDecimal getDeduction() {
        return deduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon_type.deduction
     *
     * @param deduction the value for bu_coupon_type.deduction
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setDeduction(BigDecimal deduction) {
        this.deduction = deduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon_type.screen_ids
     *
     * @return the value of bu_coupon_type.screen_ids
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public String getScreenIds() {
        return screenIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon_type.screen_ids
     *
     * @param screenIds the value for bu_coupon_type.screen_ids
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setScreenIds(String screenIds) {
        this.screenIds = screenIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon_type.commodity_ids
     *
     * @return the value of bu_coupon_type.commodity_ids
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public String getCommodityIds() {
        return commodityIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon_type.commodity_ids
     *
     * @param commodityIds the value for bu_coupon_type.commodity_ids
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setCommodityIds(String commodityIds) {
        this.commodityIds = commodityIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon_type.benison_type_ids
     *
     * @return the value of bu_coupon_type.benison_type_ids
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public String getBenisonTypeIds() {
        return benisonTypeIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon_type.benison_type_ids
     *
     * @param benisonTypeIds the value for bu_coupon_type.benison_type_ids
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setBenisonTypeIds(String benisonTypeIds) {
        this.benisonTypeIds = benisonTypeIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon_type.created_time
     *
     * @return the value of bu_coupon_type.created_time
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon_type.created_time
     *
     * @param createdTime the value for bu_coupon_type.created_time
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon_type.created_by
     *
     * @return the value of bu_coupon_type.created_by
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon_type.created_by
     *
     * @param createdBy the value for bu_coupon_type.created_by
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon_type.modified_time
     *
     * @return the value of bu_coupon_type.modified_time
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon_type.modified_time
     *
     * @param modifiedTime the value for bu_coupon_type.modified_time
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon_type.modified_by
     *
     * @return the value of bu_coupon_type.modified_by
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon_type.modified_by
     *
     * @param modifiedBy the value for bu_coupon_type.modified_by
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon_type.version
     *
     * @return the value of bu_coupon_type.version
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon_type.version
     *
     * @param version the value for bu_coupon_type.version
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon_type.delflag
     *
     * @return the value of bu_coupon_type.delflag
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public String getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon_type.delflag
     *
     * @param delflag the value for bu_coupon_type.delflag
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setDelflag(String delflag) {
        this.delflag = delflag;
    }
}