package com.liketry.interaction.benison.model;

import java.util.Date;

public class Coupon {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon.coupon_id
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private String couponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon.coupon_type_id
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private String couponTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon.coupon_code
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private String couponCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon.coupon_name
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private String couponName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon.coupon_num
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private Integer couponNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon.valid_type
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private String validType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon.publish_type
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private String publishType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon.use_type
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private String useType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon.expire
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private String expire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon.publish_target_type
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private String publishTargetType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon.personal_name
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private String personalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon.id_card
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon.merchant_name
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private String merchantName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon.business_licence
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private String businessLicence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon.valid_date
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private Date validDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon.publish_by
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private String publishBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon.publish_date
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private Date publishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon.order_code
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private String orderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon.use_time
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private Date useTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon.created_time
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon.created_by
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon.modified_time
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon.modified_by
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private String modifiedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon.version
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_coupon.delflag
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    private String delflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon.coupon_id
     *
     * @return the value of bu_coupon.coupon_id
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public String getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon.coupon_id
     *
     * @param couponId the value for bu_coupon.coupon_id
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setCouponId(String couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon.coupon_type_id
     *
     * @return the value of bu_coupon.coupon_type_id
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public String getCouponTypeId() {
        return couponTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon.coupon_type_id
     *
     * @param couponTypeId the value for bu_coupon.coupon_type_id
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setCouponTypeId(String couponTypeId) {
        this.couponTypeId = couponTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon.coupon_code
     *
     * @return the value of bu_coupon.coupon_code
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public String getCouponCode() {
        return couponCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon.coupon_code
     *
     * @param couponCode the value for bu_coupon.coupon_code
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setCouponCode(String couponCode) {
        this.couponCode = couponCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon.coupon_name
     *
     * @return the value of bu_coupon.coupon_name
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public String getCouponName() {
        return couponName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon.coupon_name
     *
     * @param couponName the value for bu_coupon.coupon_name
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setCouponName(String couponName) {
        this.couponName = couponName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon.coupon_num
     *
     * @return the value of bu_coupon.coupon_num
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public Integer getCouponNum() {
        return couponNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon.coupon_num
     *
     * @param couponNum the value for bu_coupon.coupon_num
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setCouponNum(Integer couponNum) {
        this.couponNum = couponNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon.valid_type
     *
     * @return the value of bu_coupon.valid_type
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public String getValidType() {
        return validType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon.valid_type
     *
     * @param validType the value for bu_coupon.valid_type
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setValidType(String validType) {
        this.validType = validType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon.publish_type
     *
     * @return the value of bu_coupon.publish_type
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public String getPublishType() {
        return publishType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon.publish_type
     *
     * @param publishType the value for bu_coupon.publish_type
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setPublishType(String publishType) {
        this.publishType = publishType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon.use_type
     *
     * @return the value of bu_coupon.use_type
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public String getUseType() {
        return useType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon.use_type
     *
     * @param useType the value for bu_coupon.use_type
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setUseType(String useType) {
        this.useType = useType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon.expire
     *
     * @return the value of bu_coupon.expire
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public String getExpire() {
        return expire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon.expire
     *
     * @param expire the value for bu_coupon.expire
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setExpire(String expire) {
        this.expire = expire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon.publish_target_type
     *
     * @return the value of bu_coupon.publish_target_type
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public String getPublishTargetType() {
        return publishTargetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon.publish_target_type
     *
     * @param publishTargetType the value for bu_coupon.publish_target_type
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setPublishTargetType(String publishTargetType) {
        this.publishTargetType = publishTargetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon.personal_name
     *
     * @return the value of bu_coupon.personal_name
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public String getPersonalName() {
        return personalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon.personal_name
     *
     * @param personalName the value for bu_coupon.personal_name
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setPersonalName(String personalName) {
        this.personalName = personalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon.id_card
     *
     * @return the value of bu_coupon.id_card
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon.id_card
     *
     * @param idCard the value for bu_coupon.id_card
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon.merchant_name
     *
     * @return the value of bu_coupon.merchant_name
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon.merchant_name
     *
     * @param merchantName the value for bu_coupon.merchant_name
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon.business_licence
     *
     * @return the value of bu_coupon.business_licence
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public String getBusinessLicence() {
        return businessLicence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon.business_licence
     *
     * @param businessLicence the value for bu_coupon.business_licence
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setBusinessLicence(String businessLicence) {
        this.businessLicence = businessLicence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon.valid_date
     *
     * @return the value of bu_coupon.valid_date
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public Date getValidDate() {
        return validDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon.valid_date
     *
     * @param validDate the value for bu_coupon.valid_date
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setValidDate(Date validDate) {
        this.validDate = validDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon.publish_by
     *
     * @return the value of bu_coupon.publish_by
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public String getPublishBy() {
        return publishBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon.publish_by
     *
     * @param publishBy the value for bu_coupon.publish_by
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setPublishBy(String publishBy) {
        this.publishBy = publishBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon.publish_date
     *
     * @return the value of bu_coupon.publish_date
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public Date getPublishDate() {
        return publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon.publish_date
     *
     * @param publishDate the value for bu_coupon.publish_date
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setPublishDate(Date publishDate) {
        this.publishDate = publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon.order_code
     *
     * @return the value of bu_coupon.order_code
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon.order_code
     *
     * @param orderCode the value for bu_coupon.order_code
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon.use_time
     *
     * @return the value of bu_coupon.use_time
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public Date getUseTime() {
        return useTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon.use_time
     *
     * @param useTime the value for bu_coupon.use_time
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setUseTime(Date useTime) {
        this.useTime = useTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon.created_time
     *
     * @return the value of bu_coupon.created_time
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon.created_time
     *
     * @param createdTime the value for bu_coupon.created_time
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon.created_by
     *
     * @return the value of bu_coupon.created_by
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon.created_by
     *
     * @param createdBy the value for bu_coupon.created_by
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon.modified_time
     *
     * @return the value of bu_coupon.modified_time
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon.modified_time
     *
     * @param modifiedTime the value for bu_coupon.modified_time
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon.modified_by
     *
     * @return the value of bu_coupon.modified_by
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon.modified_by
     *
     * @param modifiedBy the value for bu_coupon.modified_by
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon.version
     *
     * @return the value of bu_coupon.version
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon.version
     *
     * @param version the value for bu_coupon.version
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_coupon.delflag
     *
     * @return the value of bu_coupon.delflag
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public String getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_coupon.delflag
     *
     * @param delflag the value for bu_coupon.delflag
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    public void setDelflag(String delflag) {
        this.delflag = delflag;
    }
}