package com.liketry.interaction.benison.model;

public class DictType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_dict_type.dict_type_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String dictTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_dict_type.type_name
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_dict_type.type_parent_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String typeParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_dict_type.type_status
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String typeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_dict_type.type_seq_no
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String typeSeqNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_dict_type.type_sort_no
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private Integer typeSortNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_dict_type.dict_type_id
     *
     * @return the value of bsc_dict_type.dict_type_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getDictTypeId() {
        return dictTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_dict_type.dict_type_id
     *
     * @param dictTypeId the value for bsc_dict_type.dict_type_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setDictTypeId(String dictTypeId) {
        this.dictTypeId = dictTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_dict_type.type_name
     *
     * @return the value of bsc_dict_type.type_name
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_dict_type.type_name
     *
     * @param typeName the value for bsc_dict_type.type_name
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_dict_type.type_parent_id
     *
     * @return the value of bsc_dict_type.type_parent_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getTypeParentId() {
        return typeParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_dict_type.type_parent_id
     *
     * @param typeParentId the value for bsc_dict_type.type_parent_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setTypeParentId(String typeParentId) {
        this.typeParentId = typeParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_dict_type.type_status
     *
     * @return the value of bsc_dict_type.type_status
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getTypeStatus() {
        return typeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_dict_type.type_status
     *
     * @param typeStatus the value for bsc_dict_type.type_status
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setTypeStatus(String typeStatus) {
        this.typeStatus = typeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_dict_type.type_seq_no
     *
     * @return the value of bsc_dict_type.type_seq_no
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getTypeSeqNo() {
        return typeSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_dict_type.type_seq_no
     *
     * @param typeSeqNo the value for bsc_dict_type.type_seq_no
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setTypeSeqNo(String typeSeqNo) {
        this.typeSeqNo = typeSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_dict_type.type_sort_no
     *
     * @return the value of bsc_dict_type.type_sort_no
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public Integer getTypeSortNo() {
        return typeSortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_dict_type.type_sort_no
     *
     * @param typeSortNo the value for bsc_dict_type.type_sort_no
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setTypeSortNo(Integer typeSortNo) {
        this.typeSortNo = typeSortNo;
    }
}