package com.liketry.interaction.benison.model;

public class DictEntry {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_dict_entry.dict_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String dictId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_dict_entry.dict_type_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String dictTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_dict_entry.dict_name
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String dictName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_dict_entry.dict_status
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String dictStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_dict_entry.dict_sort_no
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private Integer dictSortNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_dict_entry.dict_parent_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String dictParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_dict_entry.dict_seq_no
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String dictSeqNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_dict_entry.dict_id
     *
     * @return the value of bsc_dict_entry.dict_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getDictId() {
        return dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_dict_entry.dict_id
     *
     * @param dictId the value for bsc_dict_entry.dict_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setDictId(String dictId) {
        this.dictId = dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_dict_entry.dict_type_id
     *
     * @return the value of bsc_dict_entry.dict_type_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getDictTypeId() {
        return dictTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_dict_entry.dict_type_id
     *
     * @param dictTypeId the value for bsc_dict_entry.dict_type_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setDictTypeId(String dictTypeId) {
        this.dictTypeId = dictTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_dict_entry.dict_name
     *
     * @return the value of bsc_dict_entry.dict_name
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getDictName() {
        return dictName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_dict_entry.dict_name
     *
     * @param dictName the value for bsc_dict_entry.dict_name
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setDictName(String dictName) {
        this.dictName = dictName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_dict_entry.dict_status
     *
     * @return the value of bsc_dict_entry.dict_status
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getDictStatus() {
        return dictStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_dict_entry.dict_status
     *
     * @param dictStatus the value for bsc_dict_entry.dict_status
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setDictStatus(String dictStatus) {
        this.dictStatus = dictStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_dict_entry.dict_sort_no
     *
     * @return the value of bsc_dict_entry.dict_sort_no
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public Integer getDictSortNo() {
        return dictSortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_dict_entry.dict_sort_no
     *
     * @param dictSortNo the value for bsc_dict_entry.dict_sort_no
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setDictSortNo(Integer dictSortNo) {
        this.dictSortNo = dictSortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_dict_entry.dict_parent_id
     *
     * @return the value of bsc_dict_entry.dict_parent_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getDictParentId() {
        return dictParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_dict_entry.dict_parent_id
     *
     * @param dictParentId the value for bsc_dict_entry.dict_parent_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setDictParentId(String dictParentId) {
        this.dictParentId = dictParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_dict_entry.dict_seq_no
     *
     * @return the value of bsc_dict_entry.dict_seq_no
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getDictSeqNo() {
        return dictSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_dict_entry.dict_seq_no
     *
     * @param dictSeqNo the value for bsc_dict_entry.dict_seq_no
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setDictSeqNo(String dictSeqNo) {
        this.dictSeqNo = dictSeqNo;
    }
}