package com.liketry.interaction.benison.model;

import java.util.Date;

public class IdentifyingCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column identifying_code.id
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column identifying_code.mobile
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column identifying_code.code
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column identifying_code.type
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column identifying_code.send_time
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column identifying_code.CREATOR
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column identifying_code.CREATE_TIME
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column identifying_code.LAST_MODBY
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    private Integer lastModby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column identifying_code.LAST_MODTIME
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    private Date lastModtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column identifying_code.id
     *
     * @return the value of identifying_code.id
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column identifying_code.id
     *
     * @param id the value for identifying_code.id
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column identifying_code.mobile
     *
     * @return the value of identifying_code.mobile
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column identifying_code.mobile
     *
     * @param mobile the value for identifying_code.mobile
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column identifying_code.code
     *
     * @return the value of identifying_code.code
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column identifying_code.code
     *
     * @param code the value for identifying_code.code
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column identifying_code.type
     *
     * @return the value of identifying_code.type
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column identifying_code.type
     *
     * @param type the value for identifying_code.type
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column identifying_code.send_time
     *
     * @return the value of identifying_code.send_time
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column identifying_code.send_time
     *
     * @param sendTime the value for identifying_code.send_time
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column identifying_code.CREATOR
     *
     * @return the value of identifying_code.CREATOR
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column identifying_code.CREATOR
     *
     * @param creator the value for identifying_code.CREATOR
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column identifying_code.CREATE_TIME
     *
     * @return the value of identifying_code.CREATE_TIME
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column identifying_code.CREATE_TIME
     *
     * @param createTime the value for identifying_code.CREATE_TIME
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column identifying_code.LAST_MODBY
     *
     * @return the value of identifying_code.LAST_MODBY
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    public Integer getLastModby() {
        return lastModby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column identifying_code.LAST_MODBY
     *
     * @param lastModby the value for identifying_code.LAST_MODBY
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    public void setLastModby(Integer lastModby) {
        this.lastModby = lastModby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column identifying_code.LAST_MODTIME
     *
     * @return the value of identifying_code.LAST_MODTIME
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    public Date getLastModtime() {
        return lastModtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column identifying_code.LAST_MODTIME
     *
     * @param lastModtime the value for identifying_code.LAST_MODTIME
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    public void setLastModtime(Date lastModtime) {
        this.lastModtime = lastModtime;
    }
}