package com.liketry.interaction.benison.model;

public class Menu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_menu.menu_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_menu.parent_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_menu.menu_name
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_menu.is_leaf
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String isLeaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_menu.menu_url
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String menuUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_menu.menu_order
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private Integer menuOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_menu.menu_status
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String menuStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_menu.icon
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_menu.is_show
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_menu.permission
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String permission;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_menu.menu_id
     *
     * @return the value of bsc_menu.menu_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_menu.menu_id
     *
     * @param menuId the value for bsc_menu.menu_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_menu.parent_id
     *
     * @return the value of bsc_menu.parent_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_menu.parent_id
     *
     * @param parentId the value for bsc_menu.parent_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_menu.menu_name
     *
     * @return the value of bsc_menu.menu_name
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_menu.menu_name
     *
     * @param menuName the value for bsc_menu.menu_name
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_menu.is_leaf
     *
     * @return the value of bsc_menu.is_leaf
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getIsLeaf() {
        return isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_menu.is_leaf
     *
     * @param isLeaf the value for bsc_menu.is_leaf
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setIsLeaf(String isLeaf) {
        this.isLeaf = isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_menu.menu_url
     *
     * @return the value of bsc_menu.menu_url
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_menu.menu_url
     *
     * @param menuUrl the value for bsc_menu.menu_url
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_menu.menu_order
     *
     * @return the value of bsc_menu.menu_order
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public Integer getMenuOrder() {
        return menuOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_menu.menu_order
     *
     * @param menuOrder the value for bsc_menu.menu_order
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setMenuOrder(Integer menuOrder) {
        this.menuOrder = menuOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_menu.menu_status
     *
     * @return the value of bsc_menu.menu_status
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getMenuStatus() {
        return menuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_menu.menu_status
     *
     * @param menuStatus the value for bsc_menu.menu_status
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setMenuStatus(String menuStatus) {
        this.menuStatus = menuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_menu.icon
     *
     * @return the value of bsc_menu.icon
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_menu.icon
     *
     * @param icon the value for bsc_menu.icon
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_menu.is_show
     *
     * @return the value of bsc_menu.is_show
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_menu.is_show
     *
     * @param isShow the value for bsc_menu.is_show
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setIsShow(String isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_menu.permission
     *
     * @return the value of bsc_menu.permission
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_menu.permission
     *
     * @param permission the value for bsc_menu.permission
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setPermission(String permission) {
        this.permission = permission;
    }
}