package com.liketry.interaction.benison.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class Order {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.order_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String orderId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.order_code
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String orderCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.transaction_no
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String transactionNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.order_type
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String orderType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.order_status
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String orderStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.book_acount_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String bookAcountId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.coupon_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String couponId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.user_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.scene
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String scene;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.user_nickname
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String userNickname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.user_phone
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String userPhone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.bless_name
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String blessName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.write_name
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String writeName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.template_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String templateId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.screen_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String screenId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.screen_name
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String screenName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.type_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String typeId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.type_name
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String typeName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.benison_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String benisonId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.benison_content
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String benisonContent;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.rule_content
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String ruleContent;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.bkimg_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String bkimgId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.bkimg_name
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String bkimgName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.bkimg_url
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String bkimgUrl;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.total_price
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private BigDecimal totalPrice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.total_orig_price
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private BigDecimal totalOrigPrice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.pay_type
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String payType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.pay_time
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String payTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.pay_price
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private BigDecimal payPrice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.confirm_status
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String confirmStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.confirm_time
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String confirmTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.confirm_by
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String confirmBy;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.confirm_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String confirmId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.confirm_reason
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String confirmReason;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.back_time
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String backTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.back_by
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String backBy;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.back_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String backId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.back_reason
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String backReason;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.back_price
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private BigDecimal backPrice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.back_remarks
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String backRemarks;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.order_descriptiion
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String orderDescriptiion;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.export_by
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String exportBy;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.export_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String exportId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.export_time
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String exportTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.result_url
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String resultUrl;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.share_url
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String shareUrl;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.promotion_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String promotionId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.created_time
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private Date createdTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.created_by
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String createdBy;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.modified_time
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private Date modifiedTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.modified_by
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String modifiedBy;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.version
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private Integer version;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order.delflag
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	private String delflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.order_id
	 * @return  the value of bu_order.order_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.order_id
	 * @param orderId  the value for bu_order.order_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.order_code
	 * @return  the value of bu_order.order_code
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getOrderCode() {
		return orderCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.order_code
	 * @param orderCode  the value for bu_order.order_code
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setOrderCode(String orderCode) {
		this.orderCode = orderCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.transaction_no
	 * @return  the value of bu_order.transaction_no
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getTransactionNo() {
		return transactionNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.transaction_no
	 * @param transactionNo  the value for bu_order.transaction_no
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setTransactionNo(String transactionNo) {
		this.transactionNo = transactionNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.order_type
	 * @return  the value of bu_order.order_type
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getOrderType() {
		return orderType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.order_type
	 * @param orderType  the value for bu_order.order_type
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setOrderType(String orderType) {
		this.orderType = orderType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.order_status
	 * @return  the value of bu_order.order_status
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getOrderStatus() {
		return orderStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.order_status
	 * @param orderStatus  the value for bu_order.order_status
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.book_acount_id
	 * @return  the value of bu_order.book_acount_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getBookAcountId() {
		return bookAcountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.book_acount_id
	 * @param bookAcountId  the value for bu_order.book_acount_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setBookAcountId(String bookAcountId) {
		this.bookAcountId = bookAcountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.coupon_id
	 * @return  the value of bu_order.coupon_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getCouponId() {
		return couponId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.coupon_id
	 * @param couponId  the value for bu_order.coupon_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setCouponId(String couponId) {
		this.couponId = couponId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.user_id
	 * @return  the value of bu_order.user_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.user_id
	 * @param userId  the value for bu_order.user_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.scene
	 * @return  the value of bu_order.scene
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getScene() {
		return scene;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.scene
	 * @param scene  the value for bu_order.scene
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setScene(String scene) {
		this.scene = scene;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.user_nickname
	 * @return  the value of bu_order.user_nickname
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getUserNickname() {
		return userNickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.user_nickname
	 * @param userNickname  the value for bu_order.user_nickname
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setUserNickname(String userNickname) {
		this.userNickname = userNickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.user_phone
	 * @return  the value of bu_order.user_phone
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getUserPhone() {
		return userPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.user_phone
	 * @param userPhone  the value for bu_order.user_phone
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.bless_name
	 * @return  the value of bu_order.bless_name
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getBlessName() {
		return blessName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.bless_name
	 * @param blessName  the value for bu_order.bless_name
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setBlessName(String blessName) {
		this.blessName = blessName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.write_name
	 * @return  the value of bu_order.write_name
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getWriteName() {
		return writeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.write_name
	 * @param writeName  the value for bu_order.write_name
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setWriteName(String writeName) {
		this.writeName = writeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.template_id
	 * @return  the value of bu_order.template_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getTemplateId() {
		return templateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.template_id
	 * @param templateId  the value for bu_order.template_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setTemplateId(String templateId) {
		this.templateId = templateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.screen_id
	 * @return  the value of bu_order.screen_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getScreenId() {
		return screenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.screen_id
	 * @param screenId  the value for bu_order.screen_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setScreenId(String screenId) {
		this.screenId = screenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.screen_name
	 * @return  the value of bu_order.screen_name
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getScreenName() {
		return screenName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.screen_name
	 * @param screenName  the value for bu_order.screen_name
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setScreenName(String screenName) {
		this.screenName = screenName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.type_id
	 * @return  the value of bu_order.type_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.type_id
	 * @param typeId  the value for bu_order.type_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setTypeId(String typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.type_name
	 * @return  the value of bu_order.type_name
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getTypeName() {
		return typeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.type_name
	 * @param typeName  the value for bu_order.type_name
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.benison_id
	 * @return  the value of bu_order.benison_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getBenisonId() {
		return benisonId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.benison_id
	 * @param benisonId  the value for bu_order.benison_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setBenisonId(String benisonId) {
		this.benisonId = benisonId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.benison_content
	 * @return  the value of bu_order.benison_content
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getBenisonContent() {
		return benisonContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.benison_content
	 * @param benisonContent  the value for bu_order.benison_content
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setBenisonContent(String benisonContent) {
		this.benisonContent = benisonContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.rule_content
	 * @return  the value of bu_order.rule_content
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getRuleContent() {
		return ruleContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.rule_content
	 * @param ruleContent  the value for bu_order.rule_content
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setRuleContent(String ruleContent) {
		this.ruleContent = ruleContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.bkimg_id
	 * @return  the value of bu_order.bkimg_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getBkimgId() {
		return bkimgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.bkimg_id
	 * @param bkimgId  the value for bu_order.bkimg_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setBkimgId(String bkimgId) {
		this.bkimgId = bkimgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.bkimg_name
	 * @return  the value of bu_order.bkimg_name
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getBkimgName() {
		return bkimgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.bkimg_name
	 * @param bkimgName  the value for bu_order.bkimg_name
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setBkimgName(String bkimgName) {
		this.bkimgName = bkimgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.bkimg_url
	 * @return  the value of bu_order.bkimg_url
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getBkimgUrl() {
		return bkimgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.bkimg_url
	 * @param bkimgUrl  the value for bu_order.bkimg_url
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setBkimgUrl(String bkimgUrl) {
		this.bkimgUrl = bkimgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.total_price
	 * @return  the value of bu_order.total_price
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public BigDecimal getTotalPrice() {
		return totalPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.total_price
	 * @param totalPrice  the value for bu_order.total_price
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setTotalPrice(BigDecimal totalPrice) {
		this.totalPrice = totalPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.total_orig_price
	 * @return  the value of bu_order.total_orig_price
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public BigDecimal getTotalOrigPrice() {
		return totalOrigPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.total_orig_price
	 * @param totalOrigPrice  the value for bu_order.total_orig_price
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setTotalOrigPrice(BigDecimal totalOrigPrice) {
		this.totalOrigPrice = totalOrigPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.pay_type
	 * @return  the value of bu_order.pay_type
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getPayType() {
		return payType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.pay_type
	 * @param payType  the value for bu_order.pay_type
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setPayType(String payType) {
		this.payType = payType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.pay_time
	 * @return  the value of bu_order.pay_time
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getPayTime() {
		return payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.pay_time
	 * @param payTime  the value for bu_order.pay_time
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setPayTime(String payTime) {
		this.payTime = payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.pay_price
	 * @return  the value of bu_order.pay_price
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public BigDecimal getPayPrice() {
		return payPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.pay_price
	 * @param payPrice  the value for bu_order.pay_price
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setPayPrice(BigDecimal payPrice) {
		this.payPrice = payPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.confirm_status
	 * @return  the value of bu_order.confirm_status
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getConfirmStatus() {
		return confirmStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.confirm_status
	 * @param confirmStatus  the value for bu_order.confirm_status
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setConfirmStatus(String confirmStatus) {
		this.confirmStatus = confirmStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.confirm_time
	 * @return  the value of bu_order.confirm_time
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getConfirmTime() {
		return confirmTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.confirm_time
	 * @param confirmTime  the value for bu_order.confirm_time
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setConfirmTime(String confirmTime) {
		this.confirmTime = confirmTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.confirm_by
	 * @return  the value of bu_order.confirm_by
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getConfirmBy() {
		return confirmBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.confirm_by
	 * @param confirmBy  the value for bu_order.confirm_by
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setConfirmBy(String confirmBy) {
		this.confirmBy = confirmBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.confirm_id
	 * @return  the value of bu_order.confirm_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getConfirmId() {
		return confirmId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.confirm_id
	 * @param confirmId  the value for bu_order.confirm_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setConfirmId(String confirmId) {
		this.confirmId = confirmId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.confirm_reason
	 * @return  the value of bu_order.confirm_reason
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getConfirmReason() {
		return confirmReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.confirm_reason
	 * @param confirmReason  the value for bu_order.confirm_reason
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setConfirmReason(String confirmReason) {
		this.confirmReason = confirmReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.back_time
	 * @return  the value of bu_order.back_time
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getBackTime() {
		return backTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.back_time
	 * @param backTime  the value for bu_order.back_time
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setBackTime(String backTime) {
		this.backTime = backTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.back_by
	 * @return  the value of bu_order.back_by
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getBackBy() {
		return backBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.back_by
	 * @param backBy  the value for bu_order.back_by
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setBackBy(String backBy) {
		this.backBy = backBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.back_id
	 * @return  the value of bu_order.back_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getBackId() {
		return backId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.back_id
	 * @param backId  the value for bu_order.back_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setBackId(String backId) {
		this.backId = backId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.back_reason
	 * @return  the value of bu_order.back_reason
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getBackReason() {
		return backReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.back_reason
	 * @param backReason  the value for bu_order.back_reason
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setBackReason(String backReason) {
		this.backReason = backReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.back_price
	 * @return  the value of bu_order.back_price
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public BigDecimal getBackPrice() {
		return backPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.back_price
	 * @param backPrice  the value for bu_order.back_price
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setBackPrice(BigDecimal backPrice) {
		this.backPrice = backPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.back_remarks
	 * @return  the value of bu_order.back_remarks
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getBackRemarks() {
		return backRemarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.back_remarks
	 * @param backRemarks  the value for bu_order.back_remarks
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setBackRemarks(String backRemarks) {
		this.backRemarks = backRemarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.order_descriptiion
	 * @return  the value of bu_order.order_descriptiion
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getOrderDescriptiion() {
		return orderDescriptiion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.order_descriptiion
	 * @param orderDescriptiion  the value for bu_order.order_descriptiion
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setOrderDescriptiion(String orderDescriptiion) {
		this.orderDescriptiion = orderDescriptiion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.export_by
	 * @return  the value of bu_order.export_by
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getExportBy() {
		return exportBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.export_by
	 * @param exportBy  the value for bu_order.export_by
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setExportBy(String exportBy) {
		this.exportBy = exportBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.export_id
	 * @return  the value of bu_order.export_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getExportId() {
		return exportId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.export_id
	 * @param exportId  the value for bu_order.export_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setExportId(String exportId) {
		this.exportId = exportId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.export_time
	 * @return  the value of bu_order.export_time
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getExportTime() {
		return exportTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.export_time
	 * @param exportTime  the value for bu_order.export_time
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setExportTime(String exportTime) {
		this.exportTime = exportTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.result_url
	 * @return  the value of bu_order.result_url
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getResultUrl() {
		return resultUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.result_url
	 * @param resultUrl  the value for bu_order.result_url
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setResultUrl(String resultUrl) {
		this.resultUrl = resultUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.share_url
	 * @return  the value of bu_order.share_url
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getShareUrl() {
		return shareUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.share_url
	 * @param shareUrl  the value for bu_order.share_url
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setShareUrl(String shareUrl) {
		this.shareUrl = shareUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.promotion_id
	 * @return  the value of bu_order.promotion_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getPromotionId() {
		return promotionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.promotion_id
	 * @param promotionId  the value for bu_order.promotion_id
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setPromotionId(String promotionId) {
		this.promotionId = promotionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.created_time
	 * @return  the value of bu_order.created_time
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public Date getCreatedTime() {
		return createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.created_time
	 * @param createdTime  the value for bu_order.created_time
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.created_by
	 * @return  the value of bu_order.created_by
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.created_by
	 * @param createdBy  the value for bu_order.created_by
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.modified_time
	 * @return  the value of bu_order.modified_time
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public Date getModifiedTime() {
		return modifiedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.modified_time
	 * @param modifiedTime  the value for bu_order.modified_time
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.modified_by
	 * @return  the value of bu_order.modified_by
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getModifiedBy() {
		return modifiedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.modified_by
	 * @param modifiedBy  the value for bu_order.modified_by
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.version
	 * @return  the value of bu_order.version
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.version
	 * @param version  the value for bu_order.version
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order.delflag
	 * @return  the value of bu_order.delflag
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public String getDelflag() {
		return delflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order.delflag
	 * @param delflag  the value for bu_order.delflag
	 * @mbggenerated  Tue Oct 17 20:22:47 CST 2017
	 */
	public void setDelflag(String delflag) {
		this.delflag = delflag;
	}

	/**
     * 订单详细列表
     */
    private List<OrderDetail> orderDetailList;
    
    /**
     * 新订单创建时�?
     */
    private String newCreateTime;
    
    public String getNewCreateTime() {
		return newCreateTime;
	}

	public void setNewCreateTime(String newCreateTime) {
		this.newCreateTime = newCreateTime;
	}

	public List<OrderDetail> getOrderDetailList() {
		return orderDetailList;
	}

	public void setOrderDetailList(List<OrderDetail> orderDetailList) {
		this.orderDetailList = orderDetailList;
	}
	
	private String fontcolor;
	
	private String fontSize;
	
	private String fontX;
	
	private String fontY;

	public String getFontcolor() {
		return fontcolor;
	}

	public void setFontcolor(String fontcolor) {
		this.fontcolor = fontcolor;
	}

	public String getFontSize() {
		return fontSize;
	}

	public void setFontSize(String fontSize) {
		this.fontSize = fontSize;
	}

	public String getFontX() {
		return fontX;
	}

	public void setFontX(String fontX) {
		this.fontX = fontX;
	}

	public String getFontY() {
		return fontY;
	}

	public void setFontY(String fontY) {
		this.fontY = fontY;
	}
	
}