package com.liketry.interaction.benison.model;

import java.math.BigDecimal;
import java.util.Date;

public class OrderDetail {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order_detail.detail_id
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	private String detailId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order_detail.order_id
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order_detail.commodity_id
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	private String commodityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order_detail.commodity_code
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	private String commodityCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order_detail.commodity_name
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	private String commodityName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order_detail.commodity_description
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	private String commodityDescription;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order_detail.commodity_price
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	private BigDecimal commodityPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order_detail.play_date
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	private String playDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order_detail.time_start
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	private String timeStart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order_detail.time_end
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	private String timeEnd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order_detail.single_time
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	private Integer singleTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order_detail.play_times
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	private Integer playTimes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order_detail.sku_id
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	private String skuId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order_detail.sku_code
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	private String skuCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order_detail.sku_name
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	private String skuName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order_detail.sku_description
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	private String skuDescription;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order_detail.sku_price
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	private BigDecimal skuPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order_detail.export_by
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	private String exportBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order_detail.export_time
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	private String exportTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order_detail.created_time
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	private Date createdTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order_detail.created_by
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	private String createdBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order_detail.modified_time
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	private Date modifiedTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order_detail.modified_by
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	private String modifiedBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order_detail.version
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_order_detail.delflag
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	private String delflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order_detail.detail_id
	 * @return  the value of bu_order_detail.detail_id
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public String getDetailId() {
		return detailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order_detail.detail_id
	 * @param detailId  the value for bu_order_detail.detail_id
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public void setDetailId(String detailId) {
		this.detailId = detailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order_detail.order_id
	 * @return  the value of bu_order_detail.order_id
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order_detail.order_id
	 * @param orderId  the value for bu_order_detail.order_id
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order_detail.commodity_id
	 * @return  the value of bu_order_detail.commodity_id
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public String getCommodityId() {
		return commodityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order_detail.commodity_id
	 * @param commodityId  the value for bu_order_detail.commodity_id
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public void setCommodityId(String commodityId) {
		this.commodityId = commodityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order_detail.commodity_code
	 * @return  the value of bu_order_detail.commodity_code
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public String getCommodityCode() {
		return commodityCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order_detail.commodity_code
	 * @param commodityCode  the value for bu_order_detail.commodity_code
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public void setCommodityCode(String commodityCode) {
		this.commodityCode = commodityCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order_detail.commodity_name
	 * @return  the value of bu_order_detail.commodity_name
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public String getCommodityName() {
		return commodityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order_detail.commodity_name
	 * @param commodityName  the value for bu_order_detail.commodity_name
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public void setCommodityName(String commodityName) {
		this.commodityName = commodityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order_detail.commodity_description
	 * @return  the value of bu_order_detail.commodity_description
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public String getCommodityDescription() {
		return commodityDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order_detail.commodity_description
	 * @param commodityDescription  the value for bu_order_detail.commodity_description
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public void setCommodityDescription(String commodityDescription) {
		this.commodityDescription = commodityDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order_detail.commodity_price
	 * @return  the value of bu_order_detail.commodity_price
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public BigDecimal getCommodityPrice() {
		return commodityPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order_detail.commodity_price
	 * @param commodityPrice  the value for bu_order_detail.commodity_price
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public void setCommodityPrice(BigDecimal commodityPrice) {
		this.commodityPrice = commodityPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order_detail.play_date
	 * @return  the value of bu_order_detail.play_date
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public String getPlayDate() {
		return playDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order_detail.play_date
	 * @param playDate  the value for bu_order_detail.play_date
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public void setPlayDate(String playDate) {
		this.playDate = playDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order_detail.time_start
	 * @return  the value of bu_order_detail.time_start
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public String getTimeStart() {
		return timeStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order_detail.time_start
	 * @param timeStart  the value for bu_order_detail.time_start
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public void setTimeStart(String timeStart) {
		this.timeStart = timeStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order_detail.time_end
	 * @return  the value of bu_order_detail.time_end
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public String getTimeEnd() {
		return timeEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order_detail.time_end
	 * @param timeEnd  the value for bu_order_detail.time_end
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public void setTimeEnd(String timeEnd) {
		this.timeEnd = timeEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order_detail.single_time
	 * @return  the value of bu_order_detail.single_time
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public Integer getSingleTime() {
		return singleTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order_detail.single_time
	 * @param singleTime  the value for bu_order_detail.single_time
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public void setSingleTime(Integer singleTime) {
		this.singleTime = singleTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order_detail.play_times
	 * @return  the value of bu_order_detail.play_times
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public Integer getPlayTimes() {
		return playTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order_detail.play_times
	 * @param playTimes  the value for bu_order_detail.play_times
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public void setPlayTimes(Integer playTimes) {
		this.playTimes = playTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order_detail.sku_id
	 * @return  the value of bu_order_detail.sku_id
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public String getSkuId() {
		return skuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order_detail.sku_id
	 * @param skuId  the value for bu_order_detail.sku_id
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public void setSkuId(String skuId) {
		this.skuId = skuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order_detail.sku_code
	 * @return  the value of bu_order_detail.sku_code
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public String getSkuCode() {
		return skuCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order_detail.sku_code
	 * @param skuCode  the value for bu_order_detail.sku_code
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public void setSkuCode(String skuCode) {
		this.skuCode = skuCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order_detail.sku_name
	 * @return  the value of bu_order_detail.sku_name
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public String getSkuName() {
		return skuName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order_detail.sku_name
	 * @param skuName  the value for bu_order_detail.sku_name
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public void setSkuName(String skuName) {
		this.skuName = skuName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order_detail.sku_description
	 * @return  the value of bu_order_detail.sku_description
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public String getSkuDescription() {
		return skuDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order_detail.sku_description
	 * @param skuDescription  the value for bu_order_detail.sku_description
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public void setSkuDescription(String skuDescription) {
		this.skuDescription = skuDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order_detail.sku_price
	 * @return  the value of bu_order_detail.sku_price
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public BigDecimal getSkuPrice() {
		return skuPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order_detail.sku_price
	 * @param skuPrice  the value for bu_order_detail.sku_price
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public void setSkuPrice(BigDecimal skuPrice) {
		this.skuPrice = skuPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order_detail.export_by
	 * @return  the value of bu_order_detail.export_by
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public String getExportBy() {
		return exportBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order_detail.export_by
	 * @param exportBy  the value for bu_order_detail.export_by
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public void setExportBy(String exportBy) {
		this.exportBy = exportBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order_detail.export_time
	 * @return  the value of bu_order_detail.export_time
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public String getExportTime() {
		return exportTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order_detail.export_time
	 * @param exportTime  the value for bu_order_detail.export_time
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public void setExportTime(String exportTime) {
		this.exportTime = exportTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order_detail.created_time
	 * @return  the value of bu_order_detail.created_time
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public Date getCreatedTime() {
		return createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order_detail.created_time
	 * @param createdTime  the value for bu_order_detail.created_time
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order_detail.created_by
	 * @return  the value of bu_order_detail.created_by
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public String getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order_detail.created_by
	 * @param createdBy  the value for bu_order_detail.created_by
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order_detail.modified_time
	 * @return  the value of bu_order_detail.modified_time
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public Date getModifiedTime() {
		return modifiedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order_detail.modified_time
	 * @param modifiedTime  the value for bu_order_detail.modified_time
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order_detail.modified_by
	 * @return  the value of bu_order_detail.modified_by
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public String getModifiedBy() {
		return modifiedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order_detail.modified_by
	 * @param modifiedBy  the value for bu_order_detail.modified_by
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order_detail.version
	 * @return  the value of bu_order_detail.version
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order_detail.version
	 * @param version  the value for bu_order_detail.version
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_order_detail.delflag
	 * @return  the value of bu_order_detail.delflag
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public String getDelflag() {
		return delflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_order_detail.delflag
	 * @param delflag  the value for bu_order_detail.delflag
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	public void setDelflag(String delflag) {
		this.delflag = delflag;
	}

	/**
	 * 祝福语内容
	 */
    private String benisonContent;
    
    public String getBenisonContent() {
		return benisonContent;
	}

	public void setBenisonContent(String benisonContent) {
		this.benisonContent = benisonContent;
	}
	
	/**
	 * 背景图
	 */
    private String bkimgUrl;
    
    public String getBkimgUrl() {
		return bkimgUrl;
	}

	public void setBkimgUrl(String bkimgUrl) {
		this.bkimgUrl = bkimgUrl;
	}
	
	/**
	 * 祝福对象
	 */
	private String blessName;
	    
    public String getBlessName() {
		return blessName;
	}

	public void setBlessName(String blessName) {
		this.blessName = blessName;
	}
	
	/**
	 * 落款人
	 */
	private String writeName;
	    
    public String getWriteName() {
		return writeName;
	}

	public void setWriteName(String writeName) {
		this.writeName = writeName;
	}


}