package com.liketry.interaction.benison.model;

import java.util.Date;

public class PromotionDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_promotion_detail.detail_id
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    private String detailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_promotion_detail.promotion_id
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    private String promotionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_promotion_detail.commodity_id
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    private String commodityId;
    
    private int commodityNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_promotion_detail.discount_ratio
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    private Float discountRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_promotion_detail.created_time
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_promotion_detail.created_by
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_promotion_detail.modified_time
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_promotion_detail.modified_by
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    private String modifiedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_promotion_detail.version
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_promotion_detail.delflag
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    private String delflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_promotion_detail.detail_id
     *
     * @return the value of bu_promotion_detail.detail_id
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    public String getDetailId() {
        return detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_promotion_detail.detail_id
     *
     * @param detailId the value for bu_promotion_detail.detail_id
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    public void setDetailId(String detailId) {
        this.detailId = detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_promotion_detail.promotion_id
     *
     * @return the value of bu_promotion_detail.promotion_id
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    public String getPromotionId() {
        return promotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_promotion_detail.promotion_id
     *
     * @param promotionId the value for bu_promotion_detail.promotion_id
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    public void setPromotionId(String promotionId) {
        this.promotionId = promotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_promotion_detail.commodity_id
     *
     * @return the value of bu_promotion_detail.commodity_id
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    public String getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_promotion_detail.commodity_id
     *
     * @param commodityId the value for bu_promotion_detail.commodity_id
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    public void setCommodityId(String commodityId) {
        this.commodityId = commodityId;
    }
    
    public int getCommodityNum() {
		return commodityNum;
	}

	public void setCommodityNum(int commodityNum) {
		this.commodityNum = commodityNum;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_promotion_detail.discount_ratio
     *
     * @return the value of bu_promotion_detail.discount_ratio
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    public Float getDiscountRatio() {
        return discountRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_promotion_detail.discount_ratio
     *
     * @param discountRatio the value for bu_promotion_detail.discount_ratio
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    public void setDiscountRatio(Float discountRatio) {
        this.discountRatio = discountRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_promotion_detail.created_time
     *
     * @return the value of bu_promotion_detail.created_time
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_promotion_detail.created_time
     *
     * @param createdTime the value for bu_promotion_detail.created_time
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_promotion_detail.created_by
     *
     * @return the value of bu_promotion_detail.created_by
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_promotion_detail.created_by
     *
     * @param createdBy the value for bu_promotion_detail.created_by
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_promotion_detail.modified_time
     *
     * @return the value of bu_promotion_detail.modified_time
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_promotion_detail.modified_time
     *
     * @param modifiedTime the value for bu_promotion_detail.modified_time
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_promotion_detail.modified_by
     *
     * @return the value of bu_promotion_detail.modified_by
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_promotion_detail.modified_by
     *
     * @param modifiedBy the value for bu_promotion_detail.modified_by
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_promotion_detail.version
     *
     * @return the value of bu_promotion_detail.version
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_promotion_detail.version
     *
     * @param version the value for bu_promotion_detail.version
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_promotion_detail.delflag
     *
     * @return the value of bu_promotion_detail.delflag
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    public String getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_promotion_detail.delflag
     *
     * @param delflag the value for bu_promotion_detail.delflag
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    public void setDelflag(String delflag) {
        this.delflag = delflag;
    }
}