package com.liketry.interaction.benison.model;

import java.util.Date;

public class Promotion {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.promotion_id
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	private String promotionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.promotion_code
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	private String promotionCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.promotion_name
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	private String promotionName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.promotion_description
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	private String promotionDescription;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.sort_num
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	private Integer sortNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.promotion_type
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	private String promotionType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.promotion_status
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	private String promotionStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.promotion_img
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	private String promotionImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.back_up
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	private String backUp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.add_time
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	private String addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.remove_time
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	private String removeTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.start_time
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	private String startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.end_time
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	private String endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.is_together
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	private String isTogether;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.created_time
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	private Date createdTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.created_by
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	private String createdBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.modified_time
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	private Date modifiedTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.modified_by
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	private String modifiedBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.version
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.delflag
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	private String delflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_promotion.promotion_id
	 * @return  the value of bu_promotion.promotion_id
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public String getPromotionId() {
		return promotionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_promotion.promotion_id
	 * @param promotionId  the value for bu_promotion.promotion_id
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public void setPromotionId(String promotionId) {
		this.promotionId = promotionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_promotion.promotion_code
	 * @return  the value of bu_promotion.promotion_code
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public String getPromotionCode() {
		return promotionCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_promotion.promotion_code
	 * @param promotionCode  the value for bu_promotion.promotion_code
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public void setPromotionCode(String promotionCode) {
		this.promotionCode = promotionCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_promotion.promotion_name
	 * @return  the value of bu_promotion.promotion_name
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public String getPromotionName() {
		return promotionName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_promotion.promotion_name
	 * @param promotionName  the value for bu_promotion.promotion_name
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public void setPromotionName(String promotionName) {
		this.promotionName = promotionName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_promotion.promotion_description
	 * @return  the value of bu_promotion.promotion_description
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public String getPromotionDescription() {
		return promotionDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_promotion.promotion_description
	 * @param promotionDescription  the value for bu_promotion.promotion_description
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public void setPromotionDescription(String promotionDescription) {
		this.promotionDescription = promotionDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_promotion.sort_num
	 * @return  the value of bu_promotion.sort_num
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public Integer getSortNum() {
		return sortNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_promotion.sort_num
	 * @param sortNum  the value for bu_promotion.sort_num
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public void setSortNum(Integer sortNum) {
		this.sortNum = sortNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_promotion.promotion_type
	 * @return  the value of bu_promotion.promotion_type
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public String getPromotionType() {
		return promotionType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_promotion.promotion_type
	 * @param promotionType  the value for bu_promotion.promotion_type
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public void setPromotionType(String promotionType) {
		this.promotionType = promotionType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_promotion.promotion_status
	 * @return  the value of bu_promotion.promotion_status
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public String getPromotionStatus() {
		return promotionStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_promotion.promotion_status
	 * @param promotionStatus  the value for bu_promotion.promotion_status
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public void setPromotionStatus(String promotionStatus) {
		this.promotionStatus = promotionStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_promotion.promotion_img
	 * @return  the value of bu_promotion.promotion_img
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public String getPromotionImg() {
		return promotionImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_promotion.promotion_img
	 * @param promotionImg  the value for bu_promotion.promotion_img
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public void setPromotionImg(String promotionImg) {
		this.promotionImg = promotionImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_promotion.back_up
	 * @return  the value of bu_promotion.back_up
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public String getBackUp() {
		return backUp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_promotion.back_up
	 * @param backUp  the value for bu_promotion.back_up
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public void setBackUp(String backUp) {
		this.backUp = backUp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_promotion.add_time
	 * @return  the value of bu_promotion.add_time
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public String getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_promotion.add_time
	 * @param addTime  the value for bu_promotion.add_time
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public void setAddTime(String addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_promotion.remove_time
	 * @return  the value of bu_promotion.remove_time
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public String getRemoveTime() {
		return removeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_promotion.remove_time
	 * @param removeTime  the value for bu_promotion.remove_time
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public void setRemoveTime(String removeTime) {
		this.removeTime = removeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_promotion.start_time
	 * @return  the value of bu_promotion.start_time
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public String getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_promotion.start_time
	 * @param startTime  the value for bu_promotion.start_time
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_promotion.end_time
	 * @return  the value of bu_promotion.end_time
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public String getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_promotion.end_time
	 * @param endTime  the value for bu_promotion.end_time
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_promotion.is_together
	 * @return  the value of bu_promotion.is_together
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public String getIsTogether() {
		return isTogether;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_promotion.is_together
	 * @param isTogether  the value for bu_promotion.is_together
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public void setIsTogether(String isTogether) {
		this.isTogether = isTogether;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_promotion.created_time
	 * @return  the value of bu_promotion.created_time
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public Date getCreatedTime() {
		return createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_promotion.created_time
	 * @param createdTime  the value for bu_promotion.created_time
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_promotion.created_by
	 * @return  the value of bu_promotion.created_by
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public String getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_promotion.created_by
	 * @param createdBy  the value for bu_promotion.created_by
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_promotion.modified_time
	 * @return  the value of bu_promotion.modified_time
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public Date getModifiedTime() {
		return modifiedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_promotion.modified_time
	 * @param modifiedTime  the value for bu_promotion.modified_time
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_promotion.modified_by
	 * @return  the value of bu_promotion.modified_by
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public String getModifiedBy() {
		return modifiedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_promotion.modified_by
	 * @param modifiedBy  the value for bu_promotion.modified_by
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_promotion.version
	 * @return  the value of bu_promotion.version
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_promotion.version
	 * @param version  the value for bu_promotion.version
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_promotion.delflag
	 * @return  the value of bu_promotion.delflag
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public String getDelflag() {
		return delflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_promotion.delflag
	 * @param delflag  the value for bu_promotion.delflag
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	public void setDelflag(String delflag) {
		this.delflag = delflag;
	}
}