package com.liketry.interaction.benison.model;

public class RoleMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_role_menu.relation_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String relationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_role_menu.role_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_role_menu.menu_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String menuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_role_menu.relation_id
     *
     * @return the value of bsc_role_menu.relation_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_role_menu.relation_id
     *
     * @param relationId the value for bsc_role_menu.relation_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setRelationId(String relationId) {
        this.relationId = relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_role_menu.role_id
     *
     * @return the value of bsc_role_menu.role_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_role_menu.role_id
     *
     * @param roleId the value for bsc_role_menu.role_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_role_menu.menu_id
     *
     * @return the value of bsc_role_menu.menu_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_role_menu.menu_id
     *
     * @param menuId the value for bsc_role_menu.menu_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }
}