package com.liketry.interaction.benison.model;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_role.role_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_role.role_code
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_role.role_name
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_role.role_status
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String roleStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_role.role_id
     *
     * @return the value of bsc_role.role_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_role.role_id
     *
     * @param roleId the value for bsc_role.role_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_role.role_code
     *
     * @return the value of bsc_role.role_code
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_role.role_code
     *
     * @param roleCode the value for bsc_role.role_code
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_role.role_name
     *
     * @return the value of bsc_role.role_name
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_role.role_name
     *
     * @param roleName the value for bsc_role.role_name
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_role.role_status
     *
     * @return the value of bsc_role.role_status
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getRoleStatus() {
        return roleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_role.role_status
     *
     * @param roleStatus the value for bsc_role.role_status
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setRoleStatus(String roleStatus) {
        this.roleStatus = roleStatus;
    }
}