package com.liketry.interaction.benison.model;

public class Screen {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_screen.screen_id
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	private String screenId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_screen.spot_id
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	private String spotId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_screen.screen_code
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	private String screenCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_screen.screen_name
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	private String screenName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_screen.screen_status
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	private String screenStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_screen.screen_img
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	private String screenImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_screen.screen_location
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	private String screenLocation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_screen.screen_longitude
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	private String screenLongitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_screen.screen_dimension
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	private String screenDimension;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_screen.screen_long
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	private String screenLong;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_screen.screen_wide
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	private String screenWide;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_screen.screen_size
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	private String screenSize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_screen.screen_resolution
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	private String screenResolution;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_screen.screen_description
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	private String screenDescription;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_screen.screen_id
	 * @return  the value of bu_screen.screen_id
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	public String getScreenId() {
		return screenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_screen.screen_id
	 * @param screenId  the value for bu_screen.screen_id
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	public void setScreenId(String screenId) {
		this.screenId = screenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_screen.spot_id
	 * @return  the value of bu_screen.spot_id
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	public String getSpotId() {
		return spotId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_screen.spot_id
	 * @param spotId  the value for bu_screen.spot_id
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	public void setSpotId(String spotId) {
		this.spotId = spotId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_screen.screen_code
	 * @return  the value of bu_screen.screen_code
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	public String getScreenCode() {
		return screenCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_screen.screen_code
	 * @param screenCode  the value for bu_screen.screen_code
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	public void setScreenCode(String screenCode) {
		this.screenCode = screenCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_screen.screen_name
	 * @return  the value of bu_screen.screen_name
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	public String getScreenName() {
		return screenName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_screen.screen_name
	 * @param screenName  the value for bu_screen.screen_name
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	public void setScreenName(String screenName) {
		this.screenName = screenName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_screen.screen_status
	 * @return  the value of bu_screen.screen_status
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	public String getScreenStatus() {
		return screenStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_screen.screen_status
	 * @param screenStatus  the value for bu_screen.screen_status
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	public void setScreenStatus(String screenStatus) {
		this.screenStatus = screenStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_screen.screen_img
	 * @return  the value of bu_screen.screen_img
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	public String getScreenImg() {
		return screenImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_screen.screen_img
	 * @param screenImg  the value for bu_screen.screen_img
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	public void setScreenImg(String screenImg) {
		this.screenImg = screenImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_screen.screen_location
	 * @return  the value of bu_screen.screen_location
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	public String getScreenLocation() {
		return screenLocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_screen.screen_location
	 * @param screenLocation  the value for bu_screen.screen_location
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	public void setScreenLocation(String screenLocation) {
		this.screenLocation = screenLocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_screen.screen_longitude
	 * @return  the value of bu_screen.screen_longitude
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	public String getScreenLongitude() {
		return screenLongitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_screen.screen_longitude
	 * @param screenLongitude  the value for bu_screen.screen_longitude
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	public void setScreenLongitude(String screenLongitude) {
		this.screenLongitude = screenLongitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_screen.screen_dimension
	 * @return  the value of bu_screen.screen_dimension
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	public String getScreenDimension() {
		return screenDimension;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_screen.screen_dimension
	 * @param screenDimension  the value for bu_screen.screen_dimension
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	public void setScreenDimension(String screenDimension) {
		this.screenDimension = screenDimension;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_screen.screen_long
	 * @return  the value of bu_screen.screen_long
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	public String getScreenLong() {
		return screenLong;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_screen.screen_long
	 * @param screenLong  the value for bu_screen.screen_long
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	public void setScreenLong(String screenLong) {
		this.screenLong = screenLong;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_screen.screen_wide
	 * @return  the value of bu_screen.screen_wide
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	public String getScreenWide() {
		return screenWide;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_screen.screen_wide
	 * @param screenWide  the value for bu_screen.screen_wide
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	public void setScreenWide(String screenWide) {
		this.screenWide = screenWide;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_screen.screen_size
	 * @return  the value of bu_screen.screen_size
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	public String getScreenSize() {
		return screenSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_screen.screen_size
	 * @param screenSize  the value for bu_screen.screen_size
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	public void setScreenSize(String screenSize) {
		this.screenSize = screenSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_screen.screen_resolution
	 * @return  the value of bu_screen.screen_resolution
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	public String getScreenResolution() {
		return screenResolution;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_screen.screen_resolution
	 * @param screenResolution  the value for bu_screen.screen_resolution
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	public void setScreenResolution(String screenResolution) {
		this.screenResolution = screenResolution;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_screen.screen_description
	 * @return  the value of bu_screen.screen_description
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	public String getScreenDescription() {
		return screenDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_screen.screen_description
	 * @param screenDescription  the value for bu_screen.screen_description
	 * @mbggenerated  Mon Jul 10 14:00:47 CST 2017
	 */
	public void setScreenDescription(String screenDescription) {
		this.screenDescription = screenDescription;
	}

	@Override
    public String toString() {
        return "Screen{" +
                "screenId='" + screenId + '\'' +
                ", spotId='" + spotId + '\'' +
                ", screenCode='" + screenCode + '\'' +
                ", screenName='" + screenName + '\'' +
                ", screenStatus='" + screenStatus + '\'' +
                ", screenLocation='" + screenLocation + '\'' +
                ", screenLongitude='" + screenLongitude + '\'' +
                ", screenDimension='" + screenDimension + '\'' +
                ", screenLong='" + screenLong + '\'' +
                ", screenWide='" + screenWide + '\'' +
                ", screenSize='" + screenSize + '\'' +
                ", screenResolution='" + screenResolution + '\'' +
                ", screenDescription='" + screenDescription + '\'' +
                '}';
    }
}