package com.liketry.interaction.benison.model;

public class Sequence {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_sequence.seq_type
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String seqType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_sequence.curr_value
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private Integer currValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_sequence.seq_status
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String seqStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_sequence.seq_type
     *
     * @return the value of bsc_sequence.seq_type
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getSeqType() {
        return seqType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_sequence.seq_type
     *
     * @param seqType the value for bsc_sequence.seq_type
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setSeqType(String seqType) {
        this.seqType = seqType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_sequence.curr_value
     *
     * @return the value of bsc_sequence.curr_value
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public Integer getCurrValue() {
        return currValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_sequence.curr_value
     *
     * @param currValue the value for bsc_sequence.curr_value
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setCurrValue(Integer currValue) {
        this.currValue = currValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_sequence.seq_status
     *
     * @return the value of bsc_sequence.seq_status
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getSeqStatus() {
        return seqStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_sequence.seq_status
     *
     * @param seqStatus the value for bsc_sequence.seq_status
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setSeqStatus(String seqStatus) {
        this.seqStatus = seqStatus;
    }
}