package com.liketry.interaction.benison.model;

public class Spot {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_spot.spot_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String spotId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_spot.spot_code
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String spotCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_spot.spot_name
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String spotName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_spot.spot_status
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String spotStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_spot.spot_province
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String spotProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_spot.spot_city
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String spotCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_spot.spot_address
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String spotAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu_spot.spot_description
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String spotDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_spot.spot_id
     *
     * @return the value of bu_spot.spot_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getSpotId() {
        return spotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_spot.spot_id
     *
     * @param spotId the value for bu_spot.spot_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setSpotId(String spotId) {
        this.spotId = spotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_spot.spot_code
     *
     * @return the value of bu_spot.spot_code
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getSpotCode() {
        return spotCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_spot.spot_code
     *
     * @param spotCode the value for bu_spot.spot_code
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setSpotCode(String spotCode) {
        this.spotCode = spotCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_spot.spot_name
     *
     * @return the value of bu_spot.spot_name
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getSpotName() {
        return spotName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_spot.spot_name
     *
     * @param spotName the value for bu_spot.spot_name
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setSpotName(String spotName) {
        this.spotName = spotName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_spot.spot_status
     *
     * @return the value of bu_spot.spot_status
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getSpotStatus() {
        return spotStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_spot.spot_status
     *
     * @param spotStatus the value for bu_spot.spot_status
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setSpotStatus(String spotStatus) {
        this.spotStatus = spotStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_spot.spot_province
     *
     * @return the value of bu_spot.spot_province
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getSpotProvince() {
        return spotProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_spot.spot_province
     *
     * @param spotProvince the value for bu_spot.spot_province
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setSpotProvince(String spotProvince) {
        this.spotProvince = spotProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_spot.spot_city
     *
     * @return the value of bu_spot.spot_city
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getSpotCity() {
        return spotCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_spot.spot_city
     *
     * @param spotCity the value for bu_spot.spot_city
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setSpotCity(String spotCity) {
        this.spotCity = spotCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_spot.spot_address
     *
     * @return the value of bu_spot.spot_address
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getSpotAddress() {
        return spotAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_spot.spot_address
     *
     * @param spotAddress the value for bu_spot.spot_address
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setSpotAddress(String spotAddress) {
        this.spotAddress = spotAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bu_spot.spot_description
     *
     * @return the value of bu_spot.spot_description
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getSpotDescription() {
        return spotDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bu_spot.spot_description
     *
     * @param spotDescription the value for bu_spot.spot_description
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setSpotDescription(String spotDescription) {
        this.spotDescription = spotDescription;
    }

    @Override
    public String toString() {
        return "Spot{" +
                "spotId='" + spotId + '\'' +
                ", spotCode='" + spotCode + '\'' +
                ", spotName='" + spotName + '\'' +
                ", spotStatus='" + spotStatus + '\'' +
                ", spotProvince='" + spotProvince + '\'' +
                ", spotCity='" + spotCity + '\'' +
                ", spotAddress='" + spotAddress + '\'' +
                ", spotDescription='" + spotDescription + '\'' +
                '}';
    }
}