package com.liketry.interaction.benison.model;

import java.util.Date;

public class Stock {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_stock.stock_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String stockId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_stock.commodity_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String commodityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_stock.stock_status
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String stockStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_stock.stock_date
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String stockDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_stock.start_time
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_stock.end_time
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_stock.sales
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private Integer sales;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_stock.stock
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private Integer stock;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_stock.schedule_status
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String scheduleStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_stock.created_time
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private Date createdTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_stock.created_by
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String createdBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_stock.modified_time
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private Date modifiedTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_stock.modified_by
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String modifiedBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_stock.version
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_stock.delflag
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String delflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_stock.stock_id
	 * @return  the value of bu_stock.stock_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getStockId() {
		return stockId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_stock.stock_id
	 * @param stockId  the value for bu_stock.stock_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setStockId(String stockId) {
		this.stockId = stockId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_stock.commodity_id
	 * @return  the value of bu_stock.commodity_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getCommodityId() {
		return commodityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_stock.commodity_id
	 * @param commodityId  the value for bu_stock.commodity_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setCommodityId(String commodityId) {
		this.commodityId = commodityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_stock.stock_status
	 * @return  the value of bu_stock.stock_status
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getStockStatus() {
		return stockStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_stock.stock_status
	 * @param stockStatus  the value for bu_stock.stock_status
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setStockStatus(String stockStatus) {
		this.stockStatus = stockStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_stock.stock_date
	 * @return  the value of bu_stock.stock_date
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getStockDate() {
		return stockDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_stock.stock_date
	 * @param stockDate  the value for bu_stock.stock_date
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setStockDate(String stockDate) {
		this.stockDate = stockDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_stock.start_time
	 * @return  the value of bu_stock.start_time
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_stock.start_time
	 * @param startTime  the value for bu_stock.start_time
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_stock.end_time
	 * @return  the value of bu_stock.end_time
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_stock.end_time
	 * @param endTime  the value for bu_stock.end_time
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_stock.sales
	 * @return  the value of bu_stock.sales
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public Integer getSales() {
		return sales;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_stock.sales
	 * @param sales  the value for bu_stock.sales
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setSales(Integer sales) {
		this.sales = sales;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_stock.stock
	 * @return  the value of bu_stock.stock
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public Integer getStock() {
		return stock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_stock.stock
	 * @param stock  the value for bu_stock.stock
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setStock(Integer stock) {
		this.stock = stock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_stock.schedule_status
	 * @return  the value of bu_stock.schedule_status
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getScheduleStatus() {
		return scheduleStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_stock.schedule_status
	 * @param scheduleStatus  the value for bu_stock.schedule_status
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setScheduleStatus(String scheduleStatus) {
		this.scheduleStatus = scheduleStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_stock.created_time
	 * @return  the value of bu_stock.created_time
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public Date getCreatedTime() {
		return createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_stock.created_time
	 * @param createdTime  the value for bu_stock.created_time
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_stock.created_by
	 * @return  the value of bu_stock.created_by
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_stock.created_by
	 * @param createdBy  the value for bu_stock.created_by
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_stock.modified_time
	 * @return  the value of bu_stock.modified_time
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public Date getModifiedTime() {
		return modifiedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_stock.modified_time
	 * @param modifiedTime  the value for bu_stock.modified_time
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_stock.modified_by
	 * @return  the value of bu_stock.modified_by
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getModifiedBy() {
		return modifiedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_stock.modified_by
	 * @param modifiedBy  the value for bu_stock.modified_by
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_stock.version
	 * @return  the value of bu_stock.version
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_stock.version
	 * @param version  the value for bu_stock.version
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_stock.delflag
	 * @return  the value of bu_stock.delflag
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getDelflag() {
		return delflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_stock.delflag
	 * @param delflag  the value for bu_stock.delflag
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setDelflag(String delflag) {
		this.delflag = delflag;
	}
}