package com.liketry.interaction.benison.model;

import java.util.Date;

public class StockDetail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_stock_detail.detail_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String detailId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_stock_detail.stock_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String stockId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_stock_detail.order_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_stock_detail.start_time
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_stock_detail.end_time
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_stock_detail.created_time
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private Date createdTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_stock_detail.created_by
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	private String createdBy;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_stock_detail.detail_id
	 * @return  the value of bu_stock_detail.detail_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getDetailId() {
		return detailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_stock_detail.detail_id
	 * @param detailId  the value for bu_stock_detail.detail_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setDetailId(String detailId) {
		this.detailId = detailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_stock_detail.stock_id
	 * @return  the value of bu_stock_detail.stock_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getStockId() {
		return stockId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_stock_detail.stock_id
	 * @param stockId  the value for bu_stock_detail.stock_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setStockId(String stockId) {
		this.stockId = stockId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_stock_detail.order_id
	 * @return  the value of bu_stock_detail.order_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_stock_detail.order_id
	 * @param orderId  the value for bu_stock_detail.order_id
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_stock_detail.start_time
	 * @return  the value of bu_stock_detail.start_time
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_stock_detail.start_time
	 * @param startTime  the value for bu_stock_detail.start_time
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_stock_detail.end_time
	 * @return  the value of bu_stock_detail.end_time
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_stock_detail.end_time
	 * @param endTime  the value for bu_stock_detail.end_time
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_stock_detail.created_time
	 * @return  the value of bu_stock_detail.created_time
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public Date getCreatedTime() {
		return createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_stock_detail.created_time
	 * @param createdTime  the value for bu_stock_detail.created_time
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_stock_detail.created_by
	 * @return  the value of bu_stock_detail.created_by
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public String getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_stock_detail.created_by
	 * @param createdBy  the value for bu_stock_detail.created_by
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
}