package com.liketry.interaction.benison.model;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.user_id
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.user_nickname
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	private String userNickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.user_pwd
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	private String userPwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.user_type
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	private String userType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.user_icon
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	private String userIcon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.user_sex
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	private String userSex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.user_birthday
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	private String userBirthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.user_province
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	private String userProvince;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.user_city
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	private String userCity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.user_address
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	private String userAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.user_mail
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	private String userMail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.user_phone
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	private String userPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.open_id
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	private String openId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.created_time
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	private Date createdTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.delflag
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	private String delflag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_user.user_id
	 * @return  the value of bu_user.user_id
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_user.user_id
	 * @param userId  the value for bu_user.user_id
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_user.user_nickname
	 * @return  the value of bu_user.user_nickname
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	public String getUserNickname() {
		return userNickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_user.user_nickname
	 * @param userNickname  the value for bu_user.user_nickname
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	public void setUserNickname(String userNickname) {
		this.userNickname = userNickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_user.user_pwd
	 * @return  the value of bu_user.user_pwd
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	public String getUserPwd() {
		return userPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_user.user_pwd
	 * @param userPwd  the value for bu_user.user_pwd
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_user.user_type
	 * @return  the value of bu_user.user_type
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	public String getUserType() {
		return userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_user.user_type
	 * @param userType  the value for bu_user.user_type
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	public void setUserType(String userType) {
		this.userType = userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_user.user_icon
	 * @return  the value of bu_user.user_icon
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	public String getUserIcon() {
		return userIcon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_user.user_icon
	 * @param userIcon  the value for bu_user.user_icon
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	public void setUserIcon(String userIcon) {
		this.userIcon = userIcon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_user.user_sex
	 * @return  the value of bu_user.user_sex
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	public String getUserSex() {
		return userSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_user.user_sex
	 * @param userSex  the value for bu_user.user_sex
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	public void setUserSex(String userSex) {
		this.userSex = userSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_user.user_birthday
	 * @return  the value of bu_user.user_birthday
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	public String getUserBirthday() {
		return userBirthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_user.user_birthday
	 * @param userBirthday  the value for bu_user.user_birthday
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	public void setUserBirthday(String userBirthday) {
		this.userBirthday = userBirthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_user.user_province
	 * @return  the value of bu_user.user_province
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	public String getUserProvince() {
		return userProvince;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_user.user_province
	 * @param userProvince  the value for bu_user.user_province
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	public void setUserProvince(String userProvince) {
		this.userProvince = userProvince;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_user.user_city
	 * @return  the value of bu_user.user_city
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	public String getUserCity() {
		return userCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_user.user_city
	 * @param userCity  the value for bu_user.user_city
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	public void setUserCity(String userCity) {
		this.userCity = userCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_user.user_address
	 * @return  the value of bu_user.user_address
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	public String getUserAddress() {
		return userAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_user.user_address
	 * @param userAddress  the value for bu_user.user_address
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_user.user_mail
	 * @return  the value of bu_user.user_mail
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	public String getUserMail() {
		return userMail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_user.user_mail
	 * @param userMail  the value for bu_user.user_mail
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	public void setUserMail(String userMail) {
		this.userMail = userMail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_user.user_phone
	 * @return  the value of bu_user.user_phone
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	public String getUserPhone() {
		return userPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_user.user_phone
	 * @param userPhone  the value for bu_user.user_phone
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_user.open_id
	 * @return  the value of bu_user.open_id
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	public String getOpenId() {
		return openId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_user.open_id
	 * @param openId  the value for bu_user.open_id
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	public void setOpenId(String openId) {
		this.openId = openId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_user.created_time
	 * @return  the value of bu_user.created_time
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	public Date getCreatedTime() {
		return createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_user.created_time
	 * @param createdTime  the value for bu_user.created_time
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bu_user.delflag
	 * @return  the value of bu_user.delflag
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	public String getDelflag() {
		return delflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bu_user.delflag
	 * @param delflag  the value for bu_user.delflag
	 * @mbggenerated  Wed Jul 19 17:59:30 CST 2017
	 */
	public void setDelflag(String delflag) {
		this.delflag = delflag;
	}
}