package com.liketry.interaction.benison.model;

public class UserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_user_role.relation_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String relationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_user_role.admin_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsc_user_role.role_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_user_role.relation_id
     *
     * @return the value of bsc_user_role.relation_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_user_role.relation_id
     *
     * @param relationId the value for bsc_user_role.relation_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setRelationId(String relationId) {
        this.relationId = relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_user_role.admin_id
     *
     * @return the value of bsc_user_role.admin_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_user_role.admin_id
     *
     * @param adminId the value for bsc_user_role.admin_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setAdminId(String adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsc_user_role.role_id
     *
     * @return the value of bsc_user_role.role_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsc_user_role.role_id
     *
     * @param roleId the value for bsc_user_role.role_id
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
}