package com.liketry.interaction.benison.dao;

import com.liketry.interaction.benison.model.BenisonTemplate;
import com.liketry.interaction.benison.model.BenisonType;
import com.liketry.interaction.benison.vo.api.BenisonVo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface BenisonTypeMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_benison_type
	 * @mbggenerated  Thu Sep 28 13:48:05 CST 2017
	 */
	int deleteByPrimaryKey(String typeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_benison_type
	 * @mbggenerated  Thu Sep 28 13:48:05 CST 2017
	 */
	int insert(BenisonType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_benison_type
	 * @mbggenerated  Thu Sep 28 13:48:05 CST 2017
	 */
	int insertSelective(BenisonType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_benison_type
	 * @mbggenerated  Thu Sep 28 13:48:05 CST 2017
	 */
	BenisonType selectByPrimaryKey(String typeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_benison_type
	 * @mbggenerated  Thu Sep 28 13:48:05 CST 2017
	 */
	int updateByPrimaryKeySelective(BenisonType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_benison_type
	 * @mbggenerated  Thu Sep 28 13:48:05 CST 2017
	 */
	int updateByPrimaryKey(BenisonType record);

    List<BenisonVo> selectTypeAndContent();
}