package com.liketry.interaction.benison.dao;

import java.util.List;

import com.liketry.interaction.benison.model.BenisonImg;

public interface BenisonImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu_benison_img
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    int deleteByPrimaryKey(String imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu_benison_img
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    int insert(BenisonImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu_benison_img
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    int insertSelective(BenisonImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu_benison_img
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    BenisonImg selectByPrimaryKey(String imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu_benison_img
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    int updateByPrimaryKeySelective(BenisonImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu_benison_img
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    int updateByPrimaryKey(BenisonImg record);
    
    /**
     * 获取背景图列表
     * @return
     */
    List<BenisonImg> findBenisonImgAll(String imgName);
}