package com.liketry.interaction.benison.dao;

import com.liketry.interaction.benison.model.Benison;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface BenisonMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_benison
	 * @mbggenerated  Thu Aug 17 11:46:58 CST 2017
	 */
	int deleteByPrimaryKey(String benisonId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_benison
	 * @mbggenerated  Thu Aug 17 11:46:58 CST 2017
	 */
	int insert(Benison record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_benison
	 * @mbggenerated  Thu Aug 17 11:46:58 CST 2017
	 */
	int insertSelective(Benison record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_benison
	 * @mbggenerated  Thu Aug 17 11:46:58 CST 2017
	 */
	Benison selectByPrimaryKey(String benisonId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_benison
	 * @mbggenerated  Thu Aug 17 11:46:58 CST 2017
	 */
	int updateByPrimaryKeySelective(Benison record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_benison
	 * @mbggenerated  Thu Aug 17 11:46:58 CST 2017
	 */
	int updateByPrimaryKey(Benison record);

	/**
     * 根据模板ID查询一条祝福语信息
     * @param benisonId
     * @return
     */
    Benison findOneBenison(@Param(value="templateId")String templateId);
}