package com.liketry.interaction.benison.dao;

import com.liketry.interaction.benison.model.BizSeqno;

public interface BizSeqnoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bsc_biz_seqno_t
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	int deleteByPrimaryKey(String seqType);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bsc_biz_seqno_t
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	int insert(BizSeqno record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bsc_biz_seqno_t
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	int insertSelective(BizSeqno record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bsc_biz_seqno_t
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	BizSeqno selectByPrimaryKey(String seqType);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bsc_biz_seqno_t
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	int updateByPrimaryKeySelective(BizSeqno record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bsc_biz_seqno_t
	 * @mbggenerated  Thu Jun 01 18:38:14 CST 2017
	 */
	int updateByPrimaryKey(BizSeqno record);
}