package com.liketry.interaction.benison.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.liketry.interaction.benison.model.CommodityCost;

public interface CommodityCostMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_commodity_cost
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	int deleteByPrimaryKey(String costId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_commodity_cost
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	int insert(CommodityCost record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_commodity_cost
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	int insertSelective(CommodityCost record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_commodity_cost
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	CommodityCost selectByPrimaryKey(String costId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_commodity_cost
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	int updateByPrimaryKeySelective(CommodityCost record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_commodity_cost
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	int updateByPrimaryKey(CommodityCost record);
	
	List<CommodityCost> getCommodityCostList(@Param(value="commodityId")String commodityId);
}