package com.liketry.interaction.benison.dao;

import com.liketry.interaction.benison.model.CommoditySku;

public interface CommoditySkuMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_commodity_sku
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	int deleteByPrimaryKey(String skuId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_commodity_sku
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	int insert(CommoditySku record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_commodity_sku
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	int insertSelective(CommoditySku record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_commodity_sku
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	CommoditySku selectByPrimaryKey(String skuId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_commodity_sku
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	int updateByPrimaryKeySelective(CommoditySku record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_commodity_sku
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	int updateByPrimaryKey(CommoditySku record);
}