package com.liketry.interaction.benison.dao;

import org.apache.ibatis.annotations.Param;

import com.liketry.interaction.benison.model.Coupon;
import com.liketry.interaction.benison.vo.api.CouponVO;

public interface CouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu_coupon
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    int deleteByPrimaryKey(String couponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu_coupon
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    int insert(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu_coupon
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    int insertSelective(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu_coupon
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    Coupon selectByPrimaryKey(String couponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu_coupon
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    int updateByPrimaryKeySelective(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu_coupon
     *
     * @mbggenerated Tue Oct 17 20:22:47 CST 2017
     */
    int updateByPrimaryKey(Coupon record);
    
    CouponVO selectByCode(@Param("code") String code);
}