package com.liketry.interaction.benison.dao;

import com.liketry.interaction.benison.model.DictEntry;

public interface DictEntryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsc_dict_entry
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    int deleteByPrimaryKey(String dictId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsc_dict_entry
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    int insert(DictEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsc_dict_entry
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    int insertSelective(DictEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsc_dict_entry
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    DictEntry selectByPrimaryKey(String dictId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsc_dict_entry
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    int updateByPrimaryKeySelective(DictEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsc_dict_entry
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    int updateByPrimaryKey(DictEntry record);
}