package com.liketry.interaction.benison.dao;

import com.liketry.interaction.benison.model.IdentifyingCode;

public interface IdentifyingCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identifying_code
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identifying_code
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    int insert(IdentifyingCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identifying_code
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    int insertSelective(IdentifyingCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identifying_code
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    IdentifyingCode selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identifying_code
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    int updateByPrimaryKeySelective(IdentifyingCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identifying_code
     *
     * @mbggenerated Sat Sep 30 10:38:14 CST 2017
     */
    int updateByPrimaryKey(IdentifyingCode record);
}