package com.liketry.interaction.benison.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.liketry.interaction.benison.model.OrderDetail;

public interface OrderDetailMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_order_detail
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	int deleteByPrimaryKey(String detailId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_order_detail
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	int insert(OrderDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_order_detail
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	int insertSelective(OrderDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_order_detail
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	OrderDetail selectByPrimaryKey(String detailId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_order_detail
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	int updateByPrimaryKeySelective(OrderDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_order_detail
	 * @mbggenerated  Mon Jun 26 16:07:20 CST 2017
	 */
	int updateByPrimaryKey(OrderDetail record);

	/**
     * 根据订单ID查询订单详细列表
     * @param orderId
     * @return
     */
    List<OrderDetail> findOrderDetailList(@Param(value="orderId")String orderId);
    
}