package com.liketry.interaction.benison.dao;

import java.util.List;

import com.liketry.interaction.benison.model.Promotion;

public interface PromotionMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_promotion
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	int deleteByPrimaryKey(String promotionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_promotion
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	int insert(Promotion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_promotion
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	int insertSelective(Promotion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_promotion
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	Promotion selectByPrimaryKey(String promotionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_promotion
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	int updateByPrimaryKeySelective(Promotion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_promotion
	 * @mbggenerated  Fri Sep 29 15:53:26 CST 2017
	 */
	int updateByPrimaryKey(Promotion record);

	/**
     * findPromotionList 
     * @return
     */
    List<Promotion> findAllPromotion();

	//获取首单9.9元活动的下单数
	int findFirstPromotionNumber();
}