package com.liketry.interaction.benison.dao;

import com.liketry.interaction.benison.model.PromotionDetail;
import com.liketry.interaction.benison.vo.api.PromotionCommodityVo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.Date;
import java.util.List;
import java.util.Map;

@Repository
public interface PromotionDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu_promotion_detail
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    int deleteByPrimaryKey(String detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu_promotion_detail
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    int insert(PromotionDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu_promotion_detail
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    int insertSelective(PromotionDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu_promotion_detail
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    PromotionDetail selectByPrimaryKey(String detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu_promotion_detail
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    int updateByPrimaryKeySelective(PromotionDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu_promotion_detail
     *
     * @mbggenerated Thu Jun 08 10:43:43 CST 2017
     */
    int updateByPrimaryKey(PromotionDetail record);

    /**
     * 返回活动商品列表 limitSize 每天最多下单限制数量
     *
     * @return
     */
    List<PromotionCommodityVo> findPromotionDetailList(@Param("promotionId") String promotionId);

    //根据活动id返回活动参与数量
    int findPartakeNumber(@Param("promotionId") String promotionId);

    List<PromotionDetail> getPromotionDetailList(Map<String, Object> map);

    /**
     * 返回活动详情
     * @param promotionId 活动id
     * @param commodityId 商品id
     * @return 返回活动详情
     */
    List<PromotionDetail> findDetails(@Param("promotionId") String promotionId, @Param("commodityId") String commodityId);
}