package com.liketry.interaction.benison.dao;

import org.apache.ibatis.annotations.Param;

import com.liketry.interaction.benison.model.Stock;

public interface StockMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_stock
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	int deleteByPrimaryKey(String stockId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_stock
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	int insert(Stock record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_stock
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	int insertSelective(Stock record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_stock
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	Stock selectByPrimaryKey(String stockId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_stock
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	int updateByPrimaryKeySelective(Stock record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bu_stock
	 * @mbggenerated  Wed May 31 18:10:18 CST 2017
	 */
	int updateByPrimaryKey(Stock record);
	
	/**
	 * 根据商品ID和播放日期查找是否有库存
	 * @param commodityId
	 * @return
	 */
	Stock findStockByCommodityId(@Param(value="commodityId") String commodityId,@Param(value="playDate") String playDate);
	
}