package com.liketry.interaction.benison.dao;

import com.liketry.interaction.benison.model.UserRole;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsc_user_role
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    int deleteByPrimaryKey(String relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsc_user_role
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsc_user_role
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    int insertSelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsc_user_role
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    UserRole selectByPrimaryKey(String relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsc_user_role
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    int updateByPrimaryKeySelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsc_user_role
     *
     * @mbggenerated Thu May 18 10:32:25 CST 2017
     */
    int updateByPrimaryKey(UserRole record);
}