package com.liketry.domain;

import java.util.Date;

import com.baomidou.mybatisplus.annotations.TableName;

import lombok.Data;
import lombok.EqualsAndHashCode;

@TableName("bu_promotion")
@Data
@EqualsAndHashCode(callSuper = false)
public class Promotion  extends BaseModel<Promotion>{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.id
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.promotion_name
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String promotionName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.promotion_produce
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String promotionProduce;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.promotion_description
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String promotionDescription;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.promotion_type
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String promotionType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.promotion_status
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String promotionStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.promotion_img
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String promotionImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.add_time
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.remove_time
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String removeTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.start_time
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.end_time
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.create_user_id
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String createUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.create_time
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.update_user_id
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String updateUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.update_time
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.version
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_promotion.delflag
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String delflag;

}