package com.liketry.domain;

import com.baomidou.mybatisplus.annotations.TableName;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.math.BigDecimal;
import java.util.Date;

@TableName("bu_rec_dis")
@Data
@EqualsAndHashCode(callSuper = false)
public class RecDis extends BaseModel<RecDis>{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_rec_dis.id
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String id;
	
	private String bankCardId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_rec_dis.rec_ids_code
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String recIdsCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_rec_dis.rec_dis_type
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String recDisType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_rec_dis.rec_dis_way
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String recDisWay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_rec_dis.rec_dis_status
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String recDisStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_rec_dis.rec_dis_price
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private BigDecimal recDisPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_rec_dis.rec_dis_balance
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private BigDecimal recDisBalance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_rec_dis.ask_time
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	
	private Date effectTime; 
	
	private Date askTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_rec_dis.rec_dis_askprice
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private BigDecimal recDisAskprice;
	
	private String commdityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_rec_dis.order_id
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_rec_dis.order_code
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String orderCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_rec_dis.touch_time
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private Date touchTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_rec_dis.touch_by
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String touchBy;
	
	private Date transAccountTime;
	
	private Date intoAccountTime;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_rec_dis.backup
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String backup;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_rec_dis.create_user_id
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String createUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_rec_dis.create_time
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_rec_dis.update_user_id
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String updateUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_rec_dis.update_time
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_rec_dis.version
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_rec_dis.delflag
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String delflag;
	
//	private String userId;

}