package com.liketry.domain;

import com.baomidou.mybatisplus.annotations.TableName;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.util.Date;

@TableName("bu_user")
@Data
@EqualsAndHashCode(callSuper = false)
public class User extends BaseModel<User>{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.id
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String id;
	
	private String loginName;
	
	private String userPwd;
	
	private String cashPwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.user_nickname
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String userNickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.user_type
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */

	private String loginSource;

	private String userType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.user_icon
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	
	private String userStatus;
	
	private String userIcon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.user_sex
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String userSex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.user_birthday
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String userBirthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.user_province
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String userProvince;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.user_city
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String userCity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.user_address
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String userAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.user_mail
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String userMail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.user_phone
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String userPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.open_id
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String openId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.create_user_id
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String createUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.create_time
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.update_user_id
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String updateUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.update_time
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.version
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bu_user.delflag
	 * @mbggenerated  Mon Aug 28 12:31:56 CST 2017
	 */
	private String delflag;

}